### ISSUE TITLE
Tutorial not working for v5.1.2 with Yarn PnP

### ISSUE THREAD

**Issue by adamsherman** [marmelab/react-admin#10154]
**What you were expecting:**
'yarn create react-admin [name]' should download and install dependencies as per tutorial. This works for yarn versions <=1.22.22 but for Yarn 2.0+ (i.e. 3.8.3 or 4.4.0 etc which uses PnP) it doesn't work.

**What happened instead:**
Complains about lodash not being declared in dependencies

**Steps to reproduce:**
yarn set version [version]
yarn create react-admin [name] (or "yarn dlx create-react-admin [name]" to be consistent with yarn modern)

Results:
```
$ yarn create react-admin test-admin
➤ YN0000: ┌ Resolution step
➤ YN0000: └ Completed in 0s 915ms
➤ YN0000: ┌ Fetch step
➤ YN0013: │ ws@npm:8.18.0 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ yallist@npm:4.0.0 can't be found in the cache and will be fetched from the remote regist
➤ YN0013: │ yargs-parser@npm:20.2.9 can't be found in the cache and will be fetched from the remote
➤ YN0013: │ yn@npm:5.0.0 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ yoga-wasm-web@npm:0.3.3 can't be found in the cache and will be fetched from the remote
➤ YN0000: └ Completed in 1s 774ms
➤ YN0000: ┌ Link step
➤ YN0000: │ ESM support for PnP uses the experimental loader API and is therefore experimental
➤ YN0000: └ Completed
➤ YN0000: Done with warnings in 2s 821ms


node:internal/modules/run_main:123
    triggerUncaughtException(
    ^
Error: create-react-admin tried to access lodash, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.

Required package: lodash (via "lodash/merge.js")
Required by: create-react-admin@npm:5.1.2 (via /Users/me/.yarn/berry/cache/create-react-admin-npm-5.1.2-219a964487-8.zip/node_modules/create-react-admin/lib/generateProject.js)

    at makeError (/private/var/folders/89/tdggkycd72q6gn8cvnw8cn0r0000gn/T/xfs-625a7cfc/dlx-24744/.pnp.cjs:10037:34)
    at resolveToUnqualified (/private/var/folders/89/tdggkycd72q6gn8cvnw8cn0r0000gn/T/xfs-625a7cfc/dlx-24744/.pnp.cjs:11714:21)
    at resolveRequest (/private/var/folders/89/tdggkycd72q6gn8cvnw8cn0r0000gn/T/xfs-625a7cfc/dlx-24744/.pnp.cjs:11843:31)
    at Object.resolveRequest (/private/var/folders/89/tdggkycd72q6gn8cvnw8cn0r0000gn/T/xfs-625a7cfc/dlx-24744/.pnp.cjs:11906:26)
    at resolve$1 (file:///private/var/folders/89/tdggkycd72q6gn8cvnw8cn0r0000gn/T/xfs-625a7cfc/dlx-24744/.pnp.loader.mjs:1994:21)
    at nextResolve (node:internal/modules/esm/hooks:746:28)
    at Hooks.resolve (node:internal/modules/esm/hooks:238:30)
    at handleMessage (node:internal/modules/esm/worker:199:24)
    at Immediate.checkForMessages (node:internal/modules/esm/worker:141:28)
    at process.processImmediate (node:internal/timers:483:21)

Node.js v22.6.0
```

**Environment**

* React-admin version: 5.1.2
* Last version that did not exhibit the issue (if applicable):
* React version: 18.3.0
* Browser: n/a
* Stack trace (in case of a JS error):

**Comment by erwanMarmelab** [comment]
Hello @adamsherman ,

Unfortunatelly, as said in [that issue](https://github.com/marmelab/react-admin/issues/7885), PnP is a burden.
Please use yarn without it to use react-admin easier.

cf #7885

**Comment by fzaninotto** [comment]
Reopening as we can add an explicit dependency to `lodash` in `create-react-admin` to solve this.
