### ISSUE TITLE
shouldRenderEmptyPage in ListView throws runtime error

### ISSUE THREAD

**Issue by tjfdud** [marmelab/react-admin#10290]
**What you were expecting:**

 We are using `InfiniteList` component from react-admin,  the current 4.16.20 version, it runs clean and no problem. 
```
<InfiniteList
          storeKey={aKey}
          perPage={DEFAULT_PER_PAGE}
          pagination={<LoadMore />}
          filters={getFilters()}
          actions={<CustomListActions />}
          empty={<EmptyChangeSet />}
          title={aTitle}
          filterDefaultValues={{ status: STATUS_VALUES.DRAFT }}
        >
          <CustomDataGrid />
 </InfiniteList>
```

**What happened instead:**

Migrating react-admin from `4.16.20` to version 5, we are experiencing runtime error when rendering `InfiniteList` component. 
![Image](https://github.com/user-attachments/assets/7e92342b-8eeb-41d0-a6f4-015ad91bede8)

**Steps to reproduce:**

The only change we made is package.json update to use the latest version `5.3.0`.

**Related code:**

![Image](https://github.com/user-attachments/assets/b61996e7-49ef-4b46-a483-a05d45088388)

Can we add a null check in this code?
https://github.com/marmelab/react-admin/blob/b921443859a4acb25e11fe2201d0be2ffa785c7e/packages/ra-ui-materialui/src/list/ListView.tsx#L79

```
insert short code snippets here
```

**Other information:**

**Environment**

* React-admin version: `5.3.0`
* Last version that did not exhibit the issue (if applicable): `4.16.20`
* React version: `18.3.1`
* Browser: 
* Stack trace (in case of a JS error):
```
Cannot read properties of undefined (reading 'length')
TypeError: Cannot read properties of undefined (reading 'length')
    at ListView (http://localhost:3005/testapp/static/js/bundle.js:136932:8)
    at renderWithHooks (http://localhost:3005/testapp/static/js/bundle.js:154232:22)
    at updateFunctionComponent (http://localhost:3005/testapp/static/js/bundle.js:157799:24)
    at beginWork (http://localhost:3005/testapp/static/js/bundle.js:159518:20)
    at HTMLUnknownElement.callCallback (http://localhost:3005/testapp/static/js/bundle.js:144488:18)
    at Object.invokeGuardedCallbackDev (http://localhost:3005/testapp/static/js/bundle.js:144532:20)
    at invokeGuardedCallback (http://localhost:3005/testapp/static/js/bundle.js:144589:35)
    at beginWork$1 (http://localhost:3005/testapp/static/js/bundle.js:164487:11)
    at performUnitOfWork (http://localhost:3005/testapp/static/js/bundle.js:163735:16)
    at workLoopSync (http://localhost:3005/testapp/static/js/bundle.js:163658:9)
```

**Comment by fzaninotto** [comment]
I can't reproduce the error you describe. You can see in the [react-admin Storybook](https://react-admin-storybook.vercel.app/?path=/story/ra-ui-materialui-list-infinitelist--aside) that `<InfiniteList>` renders without error. There must be something else in your setup that causes the bug. Therefore, we'll need a repro (i.e. based on the code of one of the stories).

As a side note, the related code that you point should never fail: if `error` is null and `isPending` is `false`, `data` should always be defined. Unless your data provider returns undefined data instead of an empty array?

**Comment by tjfdud** [comment]
@fzaninotto Thank you for the quick response.

What we know by now
- This seems to happen intermittently and mostly at the initial loading and/or after full refresh. Once ignored the error, it may work for the following attempts for a while. 
- We also ensured that our custom dataProvider always returns [] even in error situation. It works fine on our production using react-admin 4.x.
- We noticed that, for `List` component, it uses same `ListView` component WITHOUT pagination prop. When we try switching our app to use `List` component just for test/debug purposes, we see it working fine. We just see this issue with `InfiniteList`.
- When the problem happens with `InfiniteList`, we can see that `data` is `undefined`.
![Image](https://github.com/user-attachments/assets/a5985298-b84c-4d25-9f3b-92f3e6dff8cc)

**Comment by rgore13** [comment]
We have tried using the latest version (5.4.2), but we are still encountering the issue with the InfiniteList component. We have observed that the List component uses the same ListView component but without the pagination prop. When we switched our app to use the List component for testing/debugging purposes, it worked fine.

We are only seeing this issue with the InfiniteList. We also tried reproducing the issue on a sandbox, but couldn't. Since this seems to be a matter of adding a null check, is it possible to get a fix?

**Comment by fzaninotto** [comment]
I'm sorry, but we definitely need a repro.

**Comment by fzaninotto** [comment]
No news for some time, closing.
