### ISSUE TITLE
Saga error instead notification when Resource is not found

### ISSUE THREAD

**Issue by giraudvalentin** [marmelab/react-admin#1789]
**What you were expecting:**
CRUD_GET_ONE_FAILURE
A notification when CRUD action fail (see node_modules/ra-core/src/actions/dataActions.js:39)
`
onFailure: {
            notification: {
                body: 'ra.notification.item_doesnt_exist',
                level: 'warning',
            },
            redirectTo: 'list',
            refresh: true,
        }
`

**What happened instead:**
A saga error : 
`
VM16504 bundle.js:176250 uncaught at rootSaga at rootSaga 
 at admin 
 at admin 
 at takeEvery 
 at handleRedirection 
 TypeError: Cannot read property 'id' of null
    at handleRedirection$ (http://localhost:8000/static/js/bundle.js:135715:137)
    at tryCatch (http://localhost:8000/static/js/bundle.js:197616:40)
    at Generator.invoke [as _invoke] (http://localhost:8000/static/js/bundle.js:197850:22)
    at Generator.prototype.(anonymous function) [as next] (http://localhost:8000/static/js/bundle.js:197668:21)
    at next (http://localhost:8000/static/js/bundle.js:195627:27)
    at proc (http://localhost:8000/static/js/bundle.js:195586:3)
    at runForkEffect (http://localhost:8000/static/js/bundle.js:195870:19)
    at runEffect (http://localhost:8000/static/js/bundle.js:195751:872)
    at next (http://localhost:8000/static/js/bundle.js:195631:9)
    at currCb (http://localhost:8000/static/js/bundle.js:195704:7)
    at takeCb (http://localhost:8000/static/js/bundle.js:195782:152)
    at Object.put (http://localhost:8000/static/js/bundle.js:194761:16)
    at http://localhost:8000/static/js/bundle.js:194849:10
    at Array.<anonymous> (http://localhost:8000/static/js/bundle.js:194870:9)
    at Object.emit (http://localhost:8000/static/js/bundle.js:194714:13)
    at http://localhost:8000/static/js/bundle.js:195279:21
    at dispatch (http://localhost:8000/static/js/bundle.js:196892:18)
    at http://localhost:8000/static/js/bundle.js:196782:12
    at http://localhost:8000/static/js/bundle.js:195805:52
    at exec (http://localhost:8000/static/js/bundle.js:196445:5)
    at flush (http://localhost:8000/static/js/bundle.js:196486:5)
    at asap (http://localhost:8000/static/js/bundle.js:196459:5)
    at runPutEffect (http://localhost:8000/static/js/bundle.js:195802:69)
    at runEffect (http://localhost:8000/static/js/bundle.js:195751:307)
    at next (http://localhost:8000/static/js/bundle.js:195631:9)
    at currCb (http://localhost:8000/static/js/bundle.js:195704:7)
    at http://localhost:8000/static/js/bundle.js:195767:14 
`
List toolbar appear but page stay blank 

**Steps to reproduce:**
Problem is in react-admin/@master, also in the demo : https://marmelab.com/react-admin-demo/#/reviews/123123 for example

**Screenshot:**
<img width="1433" alt="capture d ecran 2018-04-26 a 18 02 22" src="https://user-images.githubusercontent.com/37140584/39317531-17023c1e-497c-11e8-9691-4979b84eb896.png">

**Other information:**
May be linked to https://github.com/marmelab/react-admin/pull/1677

**Environment**

* React-admin version: 2.0.0-beta4
* React version:~16.2.0
* Browser:Chrome Version 65.0.3325.181  (64bits)

**Comment by Masoodt** [comment]
Having this issue too!

**Comment by goussakamarwan** [comment]
Hi,
I have reached this stage ( Connecting To A Real API)
and i create All page  But iget error => Failed to fetch 

I change URL to New URL const API_URL = "https://topnewproduct.com";
See this img Thanks

- error
<img width="1280" alt="screen shot 2018-10-25 at 10 56 52 am" src="https://user-images.githubusercontent.com/7656403/47492380-c936fd00-d844-11e8-9ef8-b04b343364de.png">
- my APP.JS
<img width="1280" alt="screen shot 2018-10-25 at 10 58 32 am" src="https://user-images.githubusercontent.com/7656403/47492461-f08dca00-d844-11e8-9d9c-aab493d0e8ec.png">

**Comment by djhi** [comment]
Please don't post unrelated questions on existing issues, especially closed ones. Besides, your question should be post on Stackoverflow as explained in our issue template
