### ISSUE TITLE
Couldn't use UrlInput in the Tutorial

### ISSUE THREAD

**Issue by kidphys** [marmelab/react-admin#2002]
I'm trying out React-Amin and encounter this issue when using ArrayInput. I did a quick search through the repo and couldn't see UrlInput in the source too. 

The code: 
```
export const PostEdit = (props) => (
    <Edit title={<PostTitle />} {...props}>
        <SimpleForm>
            <ArrayInput source="backlinks">
                <SimpleFormIterator>
                    <DateInput source="date" />
                    <UrlInput source="url" />
                </SimpleFormIterator>
            </ArrayInput>
        </SimpleForm>
    </Edit>
)
```

Json data: 
```
    "posts": [
        {
            "id": 1,
            "title": "Good post",
            "backlinks": [
                {"date": "2018-01-01", "url": "http://gooo.com/1"},
                {"date": "2018-01-02", "url": "http://gooo.com/2"}
            ]
        }
    ]
```
The errror:

```

index.js:2178 uncaught at handleFetch Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `PostEdit`.
Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `PostEdit`.
    at invariant (http://localhost:3002/static/js/bundle.js:34065:15)
    at getFiberTagFromObjectType (http://localhost:3002/static/js/bundle.js:102171:9)
    at createFiberFromElement (http://localhost:3002/static/js/bundle.js:102131:20)
    at reconcileSingleElement (http://localhost:3002/static/js/bundle.js:104992:23)
    at reconcileChildFibers (http://localhost:3002/static/js/bundle.js:105049:35)
    at reconcileChildrenAtExpirationTime (http://localhost:3002/static/js/bundle.js:105420:28)
    at reconcileChildren (http://localhost:3002/static/js/bundle.js:105411:3)
    at updateHostComponent (http://localhost:3002/static/js/bundle.js:105745:3)
    at beginWork (http://localhost:3002/static/js/bundle.js:106233:14)
    at performUnitOfWork (http://localhost:3002/static/js/bundle.js:108268:12)
    at workLoop (http://localhost:3002/static/js/bundle.js:108307:24)
    at renderRoot (http://localhost:3002/static/js/bundle.js:108347:7)
    at performWorkOnRoot (http://localhost:3002/static/js/bundle.js:108965:22)
    at performWork (http://localhost:3002/static/js/bundle.js:108887:7)
    at performSyncWork (http://localhost:3002/static/js/bundle.js:108859:3)
    at requestWork (http://localhost:3002/static/js/bundle.js:108759:5)
    at scheduleWork$1 (http://localhost:3002/static/js/bundle.js:108623:11)
    at Object.enqueueSetState (http://localhost:3002/static/js/bundle.js:103704:5)
    at Connect../node_modules/react/cjs/react.development.js.Component.setState (http://localhost:3002/static/js/bundle.js:122819:16)
    at Connect.onStateChange (http://localhost:3002/static/js/bundle.js:117945:16)
    at Object.notify (http://localhost:3002/static/js/bundle.js:118604:21)
    at Subscription.notifyNestedSubs (http://localhost:3002/static/js/bundle.js:118643:20)
    at Connect.onStateChange (http://localhost:3002/static/js/bundle.js:117942:16)
    at Object.notify (http://localhost:3002/static/js/bundle.js:118604:21)
    at Subscription.notifyNestedSubs (http://localhost:3002/static/js/bundle.js:118643:20)
    at Connect.onStateChange (http://localhost:3002/static/js/bundle.js:117942:16)
    at Object.notify (http://localhost:3002/static/js/bundle.js:118604:21)
    at Subscription.notifyNestedSubs (http://localhost:3002/static/js/bundle.js:118643:20)
    at Connect.onStateChange (http://localhost:3002/static/js/bundle.js:117942:16)
    at Object.notify (http://localhost:3002/static/js/bundle.js:118604:21)
    at Subscription.notifyNestedSubs (http://localhost:3002/static/js/bundle.js:118643:20)
    at Connect.onStateChange (http://localhost:3002/static/js/bundle.js:117942:16)
    at Object.dispatch (http://localhost:3002/static/js/bundle.js:134947:7)
    at dispatch (<anonymous>:1:38399)
    at http://localhost:3002/static/js/bundle.js:119539:18
    at http://localhost:3002/static/js/bundle.js:132880:22
    at dispatch (http://localhost:3002/static/js/bundle.js:134494:18)
    at http://localhost:3002/static/js/bundle.js:134384:12
    at http://localhost:3002/static/js/bundle.js:133407:52
    at exec (http://localhost:3002/static/js/bundle.js:134047:5)
    at flush (http://localhost:3002/static/js/bundle.js:134088:5)
    at asap (http://localhost:3002/static/js/bundle.js:134061:5)
    at runPutEffect (http://localhost:3002/static/js/bundle.js:133404:69)
    at runEffect (http://localhost:3002/static/js/bundle.js:133353:307)
    at next (http://localhost:3002/static/js/bundle.js:133233:9)
    at currCb (http://localhost:3002/static/js/bundle.js:133306:7)
```

**Comment by djhi** [comment]
Hi, and thanks for your question. As explained in the [react-admin contributing guide](https://github.com/marmelab/react-admin/blob/master/README.md#contributing), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [StackOverFlow](http://stackoverflow.com/questions/tagged/react-admin).

This makes your question easy to find by the core team, and the developer community. Unlike Github, StackOverFlow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/react-admin

And once you get a response, please continue to hang out on the react-admin channel in StackOverflow. That way, you can help newcomers and share your expertise!
