### ISSUE TITLE
Cannot run react-admin on windows 

### ISSUE THREAD

**Issue by ManMohanVyas** [marmelab/react-admin#2269]
**What you were expecting:**

Clean react-admin demo installation

**What happened instead:**

> `0 info it worked if it ends with ok
> 1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
> 1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
> 1 verbose cli   'run',
> 1 verbose cli   'run-demo' ]
> 2 info using npm@5.6.0
> 3 info using node@v8.11.3
> 4 verbose run-script [ 'prerun-demo', 'run-demo', 'postrun-demo' ]
> 5 info lifecycle react-admin-lerna@~prerun-demo: react-admin-lerna@
> 6 info lifecycle react-admin-lerna@~run-demo: react-admin-lerna@
> 7 verbose lifecycle react-admin-lerna@~run-demo: unsafe-perm in lifecycle true
> 8 verbose lifecycle react-admin-lerna@~run-demo: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;D:\bl-workspace\react-admin\node_modules\.bin;C:\Program Files\Java\jdk1.8.0_181\bin\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Microsoft VS Code\bin;C:\Program Files\Git\cmd;C:\Program Files\nodejs\;C:\Users\manmohan\AppData\Local\Android\Sdk\platform-tools;D:\development\libraries\maven-3.5.4\/bin;C:\Program Files\MongoDB\Server\4.0\bin;C:\Program Files\PuTTY\;C:\Users\manmohan\AppData\Roaming\npm;%USERPROFILE%\AppData\Local\Microsoft\WindowsApps;
> 9 verbose lifecycle react-admin-lerna@~run-demo: CWD: D:\bl-workspace\react-admin
> 10 silly lifecycle react-admin-lerna@~run-demo: Args: [ '/d /s /c',
> 10 silly lifecycle   'yarn run -s build && cd examples/demo && cross-env REACT_APP_DATA_PROVIDER=rest yarn -s start' ]
> 11 silly lifecycle react-admin-lerna@~run-demo: Returned: code: 1  signal: null
> 12 info lifecycle react-admin-lerna@~run-demo: Failed to exec run-demo script
> 13 verbose stack Error: react-admin-lerna@ run-demo: `yarn run -s build && cd examples/demo && cross-env REACT_APP_DATA_PROVIDER=rest yarn -s start`
> 13 verbose stack Exit status 1
> 13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:285:16)
> 13 verbose stack     at emitTwo (events.js:126:13)
> 13 verbose stack     at EventEmitter.emit (events.js:214:7)
> 13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
> 13 verbose stack     at emitTwo (events.js:126:13)
> 13 verbose stack     at ChildProcess.emit (events.js:214:7)
> 13 verbose stack     at maybeClose (internal/child_process.js:925:16)
> 13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
> 14 verbose pkgid react-admin-lerna@
> 15 verbose cwd D:\bl-workspace\react-admin
> 16 verbose Windows_NT 10.0.16299
> 17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "run-demo"
> 18 verbose node v8.11.3
> 19 verbose npm  v5.6.0
> 20 error code ELIFECYCLE
> 21 error errno 1
> 22 error react-admin-lerna@ run-demo: `yarn run -s build && cd examples/demo && cross-env REACT_APP_DATA_PROVIDER=rest yarn -s start`
> 22 error Exit status 1
> 23 error Failed at the react-admin-lerna@ run-demo script.
> 23 error This is probably not a problem with npm. There is likely additional logging output above.
> 24 verbose exit [ 1, true ]

`

**Steps to reproduce:**

> npm install
> npm run run-demo

```


**Environment**
Windows

* React-admin version: Latest
* Last version that did not exhibit the issue (if applicable): it does exhibit
* React version:
* Browser:
* Stack trace (in case of a JS error): already attached

**Comment by djhi** [comment]
Would you mind explaining what was the mistake so that people making the same have a solution? Thanks !

**Comment by ManMohanVyas** [comment]
Demo folder renamed mistakenly, but that was real hard to find, just was a wild guess, If believe logs should proper mention these basics(File/Folder not found). Hope that helps :)
