### ISSUE TITLE
The "path" argument must be of type string. Received type undefined

### ISSUE THREAD

**Issue by zhiskar** [marmelab/react-admin#4607]
**What you were expecting:**

I am running npm run start and the application is starting on the specified port.

**What happened instead:**

Instead of this i got this error below:

```
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:112:11)
    at Object.join (path.js:1040:7)
    at noopServiceWorkerMiddleware (/Users/zhiskar/WebstormProjects/swapspace-admin-client/node_modules/react-dev-utils/noopServiceWorkerMiddleware.js:14:26)
    at Layer.handle [as handle_request] (/Users/zhiskar/WebstormProjects/swapspace-admin-client/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/zhiskar/WebstormProjects/swapspace-admin-client/node_modules/express/lib/router/index.js:317:13)
    at /Users/zhiskar/WebstormProjects/swapspace-admin-client/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/zhiskar/WebstormProjects/swapspace-admin-client/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/zhiskar/WebstormProjects/swapspace-admin-client/node_modules/express/lib/router/index.js:275:10)
    at launchEditorMiddleware (/Users/zhiskar/WebstormProjects/swapspace-admin-client/node_modules/react-dev-utils/errorOverlayMiddleware.js:20:7)
    at Layer.handle [as handle_request] (/Users/zhiskar/WebstormProjects/swapspace-admin-client/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/zhiskar/WebstormProjects/swapspace-admin-client/node_modules/express/lib/router/index.js:317:13)
    at /Users/zhiskar/WebstormProjects/swapspace-admin-client/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/zhiskar/WebstormProjects/swapspace-admin-client/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/zhiskar/WebstormProjects/swapspace-admin-client/node_modules/express/lib/router/index.js:275:10)
    at handleWebpackInternalMiddleware (/Users/zhiskar/WebstormProjects/swapspace-admin-client/node_modules/react-dev-utils/evalSourceMapMiddleware.js:42:7)
    at Layer.handle [as handle_request] (/Users/zhiskar/WebstormProjects/swapspace-admin-client/node_modules/express/lib/router/layer.js:95:5)
```

**Steps to reproduce:**

Everything worked fine yesterday, but then I upgraded to macOS Catalina 10.15.4 and this error appeared. You just need to run the application with these dependencies:
 
```
"dependencies": {
        "axios": "^0.19.2",
        "prop-types": "^15.7.2",
        "ra-data-json-server": "^3.3.3",
        "ra-data-simple-rest": "^3.3.2",
        "ra-input-rich-text": "^3.3.1",
        "react": "^16.12.0",
        "react-admin": "^3.3.3",
        "react-dom": "^16.12.0",
        "react-router-dom": "^5.1.2",
        "react-scripts": "3.3.0"
    }
```

**Environment**

* React-admin version: ^3.3.3
* Last version that did not exhibit the issue (if applicable):
* React version: ^16.12.0
* Browser: Chrome 80.0.3987.149 
* Stack trace (in case of a JS error):

**Comment by zhiskar** [comment]
Update react-scripts to 3.4.0 version solved the problem.
