### ISSUE TITLE
Failure to delete crashes the app

### ISSUE THREAD

**Issue by OoDeLally** [marmelab/react-admin#4627]
**What you were expecting:**

Clicking on the `delete` button may fail because it can happen that the user was deleted in the meantime.

![image](https://user-images.githubusercontent.com/1717629/78223533-531dd780-74c7-11ea-94ea-80258b20f85e.png)

If this happens, the graphql dataprovider sends an `user not found` error.

It should gracefully display the error (as it does for most errors), and carry on. 

**What happened instead:**

![image](https://user-images.githubusercontent.com/1717629/78223660-8f513800-74c7-11ea-992f-042de2a05718.png)

**Steps to reproduce:**

Simply make the deletion operation fail.

**Environment**

* React-admin version: 3.3.3
* React version: 16.13.1
* Browser: Chrome

```
index.js:1 Warning: Missing translation for key: "GraphQL error: User not found" 
    in Notification (created by Layout)
    in Layout (created by WithStyles(Layout))
    in WithStyles(Layout) (created by Router.Consumer)
    in Router.Consumer (created by withRouter(WithStyles(Layout)))
    in withRouter(WithStyles(Layout)) (created by ConnectFunction)
    in ConnectFunction (created by LayoutWithTheme)
    in LayoutWithTheme (created by Router.Consumer)
    in Router.Consumer (created by Route)
    in Route (created by CoreAdminRouter)
    in CoreAdminRouter (created by Router.Consumer)
    in Router.Consumer (created by Route)
    in Route (created by CoreAdminUI)
    in CoreAdminUI (created by AdminUI)
    in AdminUI (created by Admin)
    in Admin (at App.tsx:34)
    in App (at src/​index.tsx:7)
console.<computed> @ index.js:1
r @ react_devtools_backend.js:6
printWarning @ warning.js:34
warning @ warning.js:57
warn @ index.js:26
push.../node_modules/node-polyglot/index.js.Polyglot.t @ index.js:369
translate @ index.js:41
(anonymous) @ useTranslate.js:25
Notification @ Notification.js:68
renderWithHooks @ react-dom.development.js:14803
updateFunctionComponent @ react-dom.development.js:17034
beginWork @ react-dom.development.js:18610
beginWork$1 @ react-dom.development.js:23179
performUnitOfWork @ react-dom.development.js:22154
workLoopSync @ react-dom.development.js:22130
performSyncWorkOnRoot @ react-dom.development.js:21756
(anonymous) @ react-dom.development.js:11089
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11039
flushSyncCallbackQueueImpl @ react-dom.development.js:11084
flushSyncCallbackQueue @ react-dom.development.js:11072
flushPassiveEffectsImpl @ react-dom.development.js:22883
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11039
flushPassiveEffects @ react-dom.development.js:22820
(anonymous) @ react-dom.development.js:22699
workLoop @ scheduler.development.js:597
flushWork @ scheduler.development.js:552
performWorkUntilDeadline @ scheduler.development.js:164
ApolloError.ts:46 Uncaught (in promise) Error: GraphQL error: User not found
    at new ApolloError (ApolloError.ts:46)
    at Object.next (QueryManager.ts:225)
    at notifySubscription (Observable.js:135)
    at onNotify (Observable.js:179)
    at SubscriptionObserver.next (Observable.js:235)
    at observables.ts:12
    at Set.forEach (<anonymous>)
    at Object.next (observables.ts:12)
    at notifySubscription (Observable.js:135)
    at onNotify (Observable.js:179)
    at SubscriptionObserver.next (Observable.js:235)
    at httpLink.ts:142
```

**Comment by OoDeLally** [comment]
Same issue with a failure upon editting.

**Comment by fzaninotto** [comment]
Could you please paste a CodeSandbox helping to reproduce the issue?

**Comment by OoDeLally** [comment]
Any way I can quickly mockup a dataprovider, possibly a graphql one?

**Comment by fzaninotto** [comment]
Did you try https://github.com/marmelab/json-graphql-server?

**Comment by OoDeLally** [comment]
I'm afraid that is too many moving parts within one sandbox for me, sorry :/

**Comment by fzaninotto** [comment]
I couldn't reproduce using the example demo, which is using ra-data-grahql-simple.

1. clone the react-admin repo
2. make install
3. make build
4. make run-graphql-demo
5. edit file examples/demo/src/dataProvider/graphql.js, and throw an error on line 42
5. run the app, and try to delete an item

No problemo...

So you'll really need to set up an environment demonstrating the issue, because we can't reproduce it.

**Comment by OoDeLally** [comment]
`examples/demo/src/dataProvider/graphql.js` is supposed to run on the client or server side?
The error should be thrown on the server side, so that the client receive a `200 OK` with the following body:
```
{
  "errors": [
    {
      "message": "User was not found",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "data"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "stacktrace": [
            "Error: User was not found",
            "    at /home/user/flashy/core/src/user.ts:116:11",
            "    at Generator.next (<anonymous>)",
            "    at fulfilled (/home/user/flashy/core/src/user.ts:5:58)",
            "    at processTicksAndRejections (internal/process/task_queues.js:97:5)"
          ]
        }
      }
    }
  ],
  "data": {
    "data": null
  }
}```


As for checking out the repo, I wasn't able to `make` it, got the following error:

```
Exit code: 1
Command: node postinstall.js
Arguments: 
Directory: /home/user/react-admin/node_modules/full-icu
Output:
Note: Your node was not compiled with the ‘small-icu’ case, so the ICU data is not customizable through this script. Exitting.
npm install icu4c-data@66l (Node 13.12.0 and small-icu 66.1) -> icudt66l.dat
Looks like you are using yarn…
full-icu$ /usr/bin/node /usr/lib/node_modules/yarn/bin/yarn.js add icu4c-data@66l --no-lockfile --ignore-scripts
yarn add v1.22.4
info No lockfile found.
[1/4] Resolving packages...
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
error Couldn't find any versions for "icu4c-data" that matches "66l"
/home/pascal/react-admin/node_modules/full-icu/install-spawn.js:41
		throw(Error(cmdPath + ' ' + args.join(' ') + ' --> status ' + spawned.status));
		^

Error: /usr/bin/node /usr/lib/node_modules/yarn/bin/yarn.js add icu4c-data@66l --no-lockfile --ignore-scripts --> status 1
    at npmInstallNpm (/home/user/react-admin/node_modules/full-icu/install-spawn.js:41:9)
    at Object.<anonymous> (/home/user/react-admin/node_modules/full-icu/postinstall.js:68:2)
    at Module._compile (internal/modules/cjs/loader.js:1147:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:996:32)
```

**Comment by fzaninotto** [comment]
no, the code builds properly on many platforms (including on Travis, our CI).

If you can't give us a way to reproduce the issue, we can't locate or fix it...

**Comment by OoDeLally** [comment]
Did you try on your side?
1. Setup a graphql server.
1. Query it with a React admin app, go to a Edit Page of a document
1. Delete the document manually from the server's database.
1. Then back on React Admin, click on `Delete`, it will crash after the undo debouncing.

**Comment by fzaninotto** [comment]
I tried in https://github.com/marmelab/react-admin/issues/4627#issuecomment-607976019. To try further, we need a SIMPLE way to reproduce the issue. "Setup a graphql server" isn't simple enough.

**Comment by OoDeLally** [comment]
> "Setup a graphql server" isn't simple enough.
Well yeah, that is why I cannot provide you a simple codesandbox for you to play with :sweat_smile: 
I see no simpler way to reproduce the error. So we're gonna sweep it under the carpet, because reproducing it is not simple?

**Comment by OoDeLally** [comment]
In #4627 you seem to have thrown the error on the client side, haven't you?
If so, you should instead throw it on the server side.

**Comment by djhi** [comment]
> I see no simpler way to reproduce the error. So we're gonna sweep it under the carpet, because reproducing it is not simple?

We cannot fix what we cannot reproduce and our time is limited. We also have work to do with customers to pay our bills. If you can't provide a simple way for us to reproduce the issue you can't expect us to invest time on it, expect if you hire us to do so.

**Comment by OoDeLally** [comment]
Sure, I understand you have a limited time to fix all the bugs. I just figured you may want to be aware of the bugs in your framework, since each bug may reduce your customer potential. It serves nothing to "faire l'autruche". You are doing a good job so far!

**Comment by fzaninotto** [comment]
No activity for some time, no clear reproduction, so I'm closing this bug.
