### ISSUE TITLE
Deprecated findDOMNode warning in StrictMode

### ISSUE THREAD

**Issue by alextaymx** [marmelab/react-admin#5693]
This issue was already created(#4577 ) and another related issue is (#4793 ). 

I'm still having this warning:

Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of Transition which is inside StrictMode. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here: https://reactjs.org/link/strict-mode-find-node
at div
at Paper (http://localhost:3000/static/js/0.chunk.js:29516:23)
at WithStyles(ForwardRef(Paper)) (http://localhost:3000/static/js/0.chunk.js:50570:31)
at Transition (http://localhost:3000/static/js/0.chunk.js:215420:30)
at Grow (http://localhost:3000/static/js/0.chunk.js:22257:24)
at Unstable_TrapFocus (http://localhost:3000/static/js/0.chunk.js:41695:24)
at div
at Portal (http://localhost:3000/static/js/0.chunk.js:30602:24)
at Modal (http://localhost:3000/static/js/0.chunk.js:27754:83)
at Popover (http://localhost:3000/static/js/0.chunk.js:29729:22)
at WithStyles(ForwardRef(Popover)) (http://localhost:3000/static/js/0.chunk.js:50570:31)
at Menu (http://localhost:3000/static/js/0.chunk.js:26691:32)
at WithStyles(ForwardRef(Menu)) (http://localhost:3000/static/js/0.chunk.js:50570:31)
at div
at RegionMenu (http://localhost:3000/static/js/main.chunk.js:3355:84)
at div
at Toolbar (http://localhost:3000/static/js/0.chunk.js:40589:23)
at WithStyles(ForwardRef(Toolbar)) (http://localhost:3000/static/js/0.chunk.js:50570:31)
at header
at Paper (http://localhost:3000/static/js/0.chunk.js:29516:23)
at WithStyles(ForwardRef(Paper)) (http://localhost:3000/static/js/0.chunk.js:50570:31)
at AppBar (http://localhost:3000/static/js/0.chunk.js:11024:23)
at WithStyles(ForwardRef(AppBar)) (http://localhost:3000/static/js/0.chunk.js:50570:31)
at Transition (http://localhost:3000/static/js/0.chunk.js:215420:30)
at Slide (http://localhost:3000/static/js/0.chunk.js:32428:24)
at HideOnScroll (http://localhost:3000/static/js/0.chunk.js:170220:24)
at AppBar (http://localhost:3000/static/js/0.chunk.js:169494:24)
at CustomAppBar (http://localhost:3000/static/js/main.chunk.js:3518:19)
at div
at div
at LayoutWithoutTheme (http://localhost:3000/static/js/0.chunk.js:170379:24)
at WithStyles(LayoutWithoutTheme) (http://localhost:3000/static/js/0.chunk.js:50570:31)
at withRouter(WithStyles(LayoutWithoutTheme)) (http://localhost:3000/static/js/0.chunk.js:214329:37)
at Connect(withRouter(WithStyles(LayoutWithoutTheme))) (http://localhost:3000/static/js/0.chunk.js:211230:75)
at ThemeProvider (http://localhost:3000/static/js/0.chunk.js:49274:24)
at Layout (http://localhost:3000/static/js/0.chunk.js:170496:26)
at MyLayout (http://localhost:3000/static/js/main.chunk.js:3691:80)
at Route (http://localhost:3000/static/js/0.chunk.js:214072:29)
at Switch (http://localhost:3000/static/js/0.chunk.js:214274:29)
at div
at CoreAdminRouter (http://localhost:3000/static/js/0.chunk.js:138254:87)
at Route (http://localhost:3000/static/js/0.chunk.js:214072:29)
at Switch (http://localhost:3000/static/js/0.chunk.js:214274:29)
at CoreAdminUI (http://localhost:3000/static/js/0.chunk.js:138459:15)
at AdminUI
at Router (http://localhost:3000/static/js/0.chunk.js:213707:30)
at ConnectedRouter (http://localhost:3000/static/js/0.chunk.js:75959:7)
at ConnectedRouterWithContext (http://localhost:3000/static/js/0.chunk.js:76064:25)
at Connect(ConnectedRouterWithContext) (http://localhost:3000/static/js/0.chunk.js:211230:75)
at TranslationProvider (http://localhost:3000/static/js/0.chunk.js:145382:28)
at Provider (http://localhost:3000/static/js/0.chunk.js:210943:20)
at CoreAdminContext (http://localhost:3000/static/js/0.chunk.js:138023:25)
at AdminContext
at Admin (http://localhost:3000/static/js/0.chunk.js:176761:22)
at ApolloProvider (http://localhost:3000/static/js/0.chunk.js:6197:19)
at App (http://localhost:3000/static/js/main.chunk.js:183:97)

**Comment by alextaymx** [comment]
this version : 
"react-transition-group": "^4.4.1" 
is in the package.json of ra-ui-materialui

**Comment by JohnAntonusMaximus** [comment]
+1, getting this issue too.

**Comment by lukynmatuska** [comment]
+1, getting this issue too.
