### ISSUE TITLE
Crash when adding validation messages to inputs within ArrayInputs

### ISSUE THREAD

**Issue by andrico1234** [marmelab/react-admin#6128]
**What you were expecting:**
Since React 3.14.x, if an Inputs that lives inside ArrayInputs has an error message assigned it it, the app crashes on Save.

here's a video of this happening

https://user-images.githubusercontent.com/17087167/113691881-d5397100-96c4-11eb-9e7c-55eaf6b2102b.mov

I've tested this with both TextInputs and SelectInputs and they break, leading me to believe it's an issue with the `ArrayInput`. 

I've created a repro in [here](https://github.com/andrico1234/react-admin/tree/repro/nested-errors-in-arrays), you can run it and test the `PostEdit` page. 

This is the code causes the break

```tsx
import * as React from 'react';
import {
    ArrayInput,
    Edit,
    FormTab,
    SimpleFormIterator,
    TextInput,
    TabbedForm,
} from 'react-admin'; // eslint-disable-line import/no-unresolved

function validate(values: any) {
    const { authors } = values;
    const errors: any = {
        authors: [],
    };

    // works fine
    errors.singleRole = ['A role already exists with this author.'];

    // this doesn't works
    if (authors) {
        authors.forEach((author: any, i: number) => {
            if (!author) return;

            const error: any = {};

            if (author.role) {
                error.role = ['A role already exists with this author.'];
                errors.authors = [];
                errors.authors[i] = error;
            }
        });
    }

    return errors;
}

const PostEdit = ({ permissions, ...props }) => (
    <Edit {...props}>
        <TabbedForm warnWhenUnsavedChanges validate={validate}>
            <FormTab label="post.form.summary">
                {/* works fine */}
                <TextInput source="singleRole" />

                {/* doesn't work */}
                <ArrayInput source="authors">
                    <SimpleFormIterator>
                        <TextInput source="role" />
                    </SimpleFormIterator>
                </ArrayInput>
            </FormTab>
        </TabbedForm>
    </Edit>
);

export default PostEdit;

```

**Environment**

* React-admin version: 3.14.1+
* Last version that did not exhibit the issue (if applicable): 3.14.0
* React version: 17
* Browser: Chrome
* Stack trace (in case of a JS error):

```
Error: Objects are not valid as a React child (found: object with keys {role}). If you meant to render a collection of children, use an array instead.

    at ValidationError (http://localhost:8080/@fs/Users/andrico/Documents/Coding/react-admin/packages/ra-core/src/form/ValidationError.tsx:8:3)
    at InputHelperText (http://localhost:8080/@fs/Users/andrico/Documents/Coding/react-admin/packages/ra-ui-materialui/src/input/InputHelperText.tsx:8:3)
    at p
    at FormHelperText2 (http://localhost:8080/node_modules/.vite/chunk.HGLZTGBU.js?v=335e2996:61:5)
    at WithStyles(ForwardRef(FormHelperText2)) (http://localhost:8080/node_modules/.vite/chunk.POGTIVQJ.js?v=335e2996:362:31)
    at div
    at FormControl2 (http://localhost:8080/node_modules/.vite/chunk.4G2RE2EP.js?v=335e2996:73:5)
    at WithStyles(ForwardRef(FormControl2)) (http://localhost:8080/node_modules/.vite/chunk.POGTIVQJ.js?v=335e2996:362:31)
    at ArrayInput (http://localhost:8080/@fs/Users/andrico/Documents/Coding/react-admin/packages/ra-ui-materialui/src/input/ArrayInput.tsx:19:3)
    at div
    at FormInput (http://localhost:8080/@fs/Users/andrico/Documents/Coding/react-admin/packages/ra-ui-materialui/src/form/FormInput.tsx:30:5)
    at span
    at FormGroupContextProvider (http://localhost:8080/@fs/Users/andrico/Documents/Coding/react-admin/packages/ra-core/src/form/FormGroupContextProvider.tsx:10:3)
    at FormTab (http://localhost:8080/@fs/Users/andrico/Documents/Coding/react-admin/packages/ra-ui-materialui/src/form/FormTab.tsx:12:3)
    at Route2 (http://localhost:8080/node_modules/.vite/chunk.3HHKMOQI.js?v=335e2996:736:29)
    at div
    at form
    at TabbedFormView (http://localhost:8080/@fs/Users/andrico/Documents/Coding/react-admin/packages/ra-ui-materialui/src/form/TabbedFormView.tsx:24:5)
    at FormView (http://localhost:8080/@fs/Users/andrico/Documents/Coding/react-admin/packages/ra-core/src/form/FormWithRedirect.tsx:142:3)
    at ReactFinalForm (http://localhost:8080/node_modules/.vite/chunk.WW5ACNJ3.js?v=335e2996:124:22)
    at FormContextProvider (http://localhost:8080/@fs/Users/andrico/Documents/Coding/react-admin/packages/ra-core/src/form/FormContextProvider.tsx:5:3)
    at FormWithRedirect (http://localhost:8080/@fs/Users/andrico/Documents/Coding/react-admin/packages/ra-core/src/form/FormWithRedirect.tsx:25:3)
    at TabbedForm
    at div
    at Paper2 (http://localhost:8080/node_modules/.vite/chunk.3WWDLCXX.js?v=335e2996:52:5)
    at WithStyles(ForwardRef(Paper2)) (http://localhost:8080/node_modules/.vite/chunk.POGTIVQJ.js?v=335e2996:362:31)
    at Card2 (http://localhost:8080/node_modules/.vite/chunk.DGLX363H.js?v=335e2996:36:5)
    at WithStyles(ForwardRef(Card2)) (http://localhost:8080/node_modules/.vite/chunk.POGTIVQJ.js?v=335e2996:362:31)
    at div
    at div
```

**Comment by andrico1234** [comment]
Found the root of the problem, opening up an MR now
