### ISSUE TITLE
ReferenceInput + AutocompleteInput does not display current value and has duplicate keys

### ISSUE THREAD

**Issue by boks1971** [marmelab/react-admin#6408]
**What you were expecting:**
- `AutocompleteInput` inside `ReferenceInput` shows current value (useful in Edit mode).
- The current value and search fetched records are de-duped to avoid the duplicate key.

**What happened instead:**
- Do not see the current value on load
- See dupe of current value in the list if the fetched records also has the value.

Also see the following errors in console
```
Warning: Encountered two children with the same key, `100`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.
    at div
    at Paper (webpack-internal:///./node_modules/@material-ui/core/esm/Paper/Paper.js:48:23)
    at WithStyles (webpack-internal:///./node_modules/@material-ui/styles/esm/withStyles/withStyles.js:61:31)
    at div
    at div
    at Portal (webpack-internal:///./node_modules/@material-ui/core/esm/Portal/Portal.js:31:24)
    at Popper (webpack-internal:///./node_modules/@material-ui/core/esm/Popper/Popper.js:63:24)
    at AutocompleteSuggestionList (webpack-internal:///./node_modules/ra-ui-materialui/esm/input/AutocompleteSuggestionList.js:33:26)
    at div
    at Downshift (webpack-internal:///./node_modules/downshift/dist/downshift.esm.js:449:28)
    at AutocompleteInput (webpack-internal:///./node_modules/ra-ui-materialui/esm/input/AutocompleteInput.js:162:28)
    at ListContextProvider (webpack-internal:///./node_modules/ra-core/esm/controller/ListContextProvider.js:41:20)
    at ResourceContextProvider (webpack-internal:///./node_modules/ra-core/esm/core/ResourceContextProvider.js:11:23)
    at ReferenceInputView (webpack-internal:///./node_modules/ra-ui-materialui/esm/input/ReferenceInput.js:159:25)
    at ReferenceInput (webpack-internal:///./node_modules/ra-ui-materialui/esm/input/ReferenceInput.js:119:21)
    at div
    at FormInput (webpack-internal:///./node_modules/ra-ui-materialui/esm/form/FormInput.js:46:23)
    at div
    at CardContent (webpack-internal:///./node_modules/@material-ui/core/esm/CardContent/CardContent.js:29:23)
    at WithStyles (webpack-internal:///./node_modules/@material-ui/styles/esm/withStyles/withStyles.js:61:31)
    at CardContentInner (webpack-internal:///./node_modules/ra-ui-materialui/esm/layout/CardContentInner.js:42:27)
    at form
    at SimpleFormView (webpack-internal:///./node_modules/ra-ui-materialui/esm/form/SimpleFormView.js:44:23)
    at FormView (webpack-internal:///./node_modules/ra-core/esm/form/FormWithRedirect.js:161:21)
    at ReactFinalForm (webpack-internal:///./node_modules/react-final-form/dist/react-final-form.es.js:164:20)
    at FormContextProvider (webpack-internal:///./node_modules/ra-core/esm/form/FormContextProvider.js:17:23)
    at FormWithRedirect (webpack-internal:///./node_modules/ra-core/esm/form/FormWithRedirect.js:76:20)
    at SimpleForm
    at div
    at Paper (webpack-internal:///./node_modules/@material-ui/core/esm/Paper/Paper.js:48:23)
    at WithStyles (webpack-internal:///./node_modules/@material-ui/styles/esm/withStyles/withStyles.js:61:31)
    at Card (webpack-internal:///./node_modules/@material-ui/core/esm/Card/Card.js:28:23)
    at WithStyles (webpack-internal:///./node_modules/@material-ui/styles/esm/withStyles/withStyles.js:61:31)
    at div
    at div
    at EditView (webpack-internal:///./node_modules/ra-ui-materialui/esm/detail/EditView.js:51:25)
    at RecordContextProvider (webpack-internal:///./node_modules/ra-core/esm/controller/RecordContext.js:31:23)
    at SaveContextProvider (webpack-internal:///./node_modules/ra-core/esm/controller/details/SaveContext.js:17:23)
    at EditContextProvider (webpack-internal:///./node_modules/ra-core/esm/controller/details/EditContextProvider.js:38:23)
    at ResourceContextProvider (webpack-internal:///./node_modules/ra-core/esm/core/ResourceContextProvider.js:11:23)
    at Edit (webpack-internal:///./node_modules/ra-ui-materialui/esm/detail/Edit.js:73:74)
    at WaitlistEdit
    at WithPermissions (webpack-internal:///./node_modules/ra-core/esm/auth/WithPermissions.js:69:25)
    at Route (webpack-internal:///./node_modules/react-router/esm/react-router.js:466:29)
    at Switch (webpack-internal:///./node_modules/react-router/esm/react-router.js:672:29)
    at ResourceContextProvider (webpack-internal:///./node_modules/ra-core/esm/core/ResourceContextProvider.js:11:23)
    at ResourceRoutes (webpack-internal:///./node_modules/ra-core/esm/core/Resource.js:57:19)
    at Resource (webpack-internal:///./node_modules/ra-core/esm/core/Resource.js:85:17)
    at Route (webpack-internal:///./node_modules/react-router/esm/react-router.js:466:29)
    at Switch (webpack-internal:///./node_modules/react-router/esm/react-router.js:672:29)
    at RoutesWithLayout (webpack-internal:///./node_modules/ra-core/esm/core/RoutesWithLayout.js:22:23)
    at div
    at main
    at div
    at div
    at LayoutWithoutTheme (webpack-internal:///./node_modules/ra-ui-materialui/esm/layout/Layout.js:124:28)
    at WithStyles (webpack-internal:///./node_modules/@material-ui/styles/esm/withStyles/withStyles.js:61:31)
    at C (webpack-internal:///./node_modules/react-router/esm/react-router.js:727:37)
    at ConnectFunction (webpack-internal:///./node_modules/react-redux/es/components/connectAdvanced.js:233:68)
    at ThemeProvider (webpack-internal:///./node_modules/@material-ui/styles/esm/ThemeProvider/ThemeProvider.js:42:24)
    at Layout (webpack-internal:///./node_modules/ra-ui-materialui/esm/layout/Layout.js:197:28)
    at Route (webpack-internal:///./node_modules/react-router/esm/react-router.js:466:29)
    at Switch (webpack-internal:///./node_modules/react-router/esm/react-router.js:672:29)
    at div
    at CoreAdminRouter (webpack-internal:///./node_modules/ra-core/esm/core/CoreAdminRouter.js:63:82)
    at Route (webpack-internal:///./node_modules/react-router/esm/react-router.js:466:29)
    at Switch (webpack-internal:///./node_modules/react-router/esm/react-router.js:672:29)
    at CoreAdminUI (webpack-internal:///./node_modules/ra-core/esm/core/CoreAdminUI.js:28:17)
    at AdminUI
    at Router (webpack-internal:///./node_modules/react-router/esm/react-router.js:95:30)
    at ConnectedRouter (webpack-internal:///./node_modules/connected-react-router/esm/ConnectedRouter.js:63:7)
    at ConnectedRouterWithContext (webpack-internal:///./node_modules/connected-react-router/esm/ConnectedRouter.js:187:25)
    at ConnectFunction (webpack-internal:///./node_modules/react-redux/es/components/connectAdvanced.js:233:68)
    at TranslationProvider (webpack-internal:///./node_modules/ra-core/esm/i18n/TranslationProvider.js:33:30)
    at Provider (webpack-internal:///./node_modules/react-redux/es/components/Provider.js:16:20)
    at CoreAdminContext (webpack-internal:///./node_modules/ra-core/esm/core/CoreAdminContext.js:21:27)
    at AdminContext
    at Admin (webpack-internal:///./node_modules/react-admin/esm/Admin.js:89:24)
    at ReactAdmin
    at LoadableComponent (webpack-internal:///./node_modules/next/dist/next-server/lib/loadable.js:188:37)
    at AdminPage
    at div
    at ClerkContextWrapper (webpack-internal:///./node_modules/@clerk/clerk-react/dist/clerk-react.esm.js:806:30)
    at ClerkProviderBase (webpack-internal:///./node_modules/@clerk/clerk-react/dist/clerk-react.esm.js:861:61)
    at Hoc (webpack-internal:///./node_modules/@clerk/clerk-react/dist/clerk-react.esm.js:161:5)
    at LeapApp (webpack-internal:///./pages/_app.tsx:67:24)
    at ErrorBoundary (webpack-internal:///./node_modules/@next/react-dev-overlay/lib/internal/ErrorBoundary.js:26:47)
    at ReactDevOverlay (webpack-internal:///./node_modules/@next/react-dev-overlay/lib/internal/ReactDevOverlay.js:86:23)
    at Container (webpack-internal:///./node_modules/next/dist/client/index.js:155:5)
    at AppContainer (webpack-internal:///./node_modules/next/dist/client/index.js:643:24)
    at Root (webpack-internal:///./node_modules/next/dist/client/index.js:779:25)
printWarning @ react-dom.development.js?61bb:67
error @ react-dom.development.js?61bb:43
warnOnInvalidKey @ react-dom.development.js?61bb:13620
reconcileChildrenArray @ react-dom.development.js?61bb:13651
reconcileChildFibers @ react-dom.development.js?61bb:14125
reconcileChildren @ react-dom.development.js?61bb:16997
updateHostComponent @ react-dom.development.js?61bb:17632
beginWork @ react-dom.development.js?61bb:19080
beginWork$1 @ react-dom.development.js?61bb:23940
performUnitOfWork @ react-dom.development.js?61bb:22776
workLoopSync @ react-dom.development.js?61bb:22707
renderRootSync @ react-dom.development.js?61bb:22670
performSyncWorkOnRoot @ react-dom.development.js?61bb:22293
eval @ react-dom.development.js?61bb:11327
unstable_runWithPriority @ scheduler.development.js?3069:468
runWithPriority$1 @ react-dom.development.js?61bb:11276
flushSyncCallbackQueueImpl @ react-dom.development.js?61bb:11322
flushSyncCallbackQueue @ react-dom.development.js?61bb:11309
discreteUpdates$1 @ react-dom.development.js?61bb:22420
discreteUpdates @ react-dom.development.js?61bb:3756
dispatchDiscreteEvent @ react-dom.development.js?61bb:5889
react-dom.development.js?61bb:67 Warning: A component is changing a controlled input to be uncontrolled. This is likely caused by the value changing from a defined to undefined, which should not happen. Decide between using a controlled or uncontrolled input element for the lifetime of the component. More info: https://reactjs.org/link/controlled-components
    at input
    at div
    at InputBase (webpack-internal:///./node_modules/@material-ui/core/esm/InputBase/InputBase.js:214:30)
    at WithStyles (webpack-internal:///./node_modules/@material-ui/styles/esm/withStyles/withStyles.js:61:31)
    at FilledInput (webpack-internal:///./node_modules/@material-ui/core/esm/FilledInput/FilledInput.js:184:32)
    at WithStyles (webpack-internal:///./node_modules/@material-ui/styles/esm/withStyles/withStyles.js:61:31)
    at div
    at FormControl (webpack-internal:///./node_modules/@material-ui/core/esm/FormControl/FormControl.js:84:24)
    at WithStyles (webpack-internal:///./node_modules/@material-ui/styles/esm/withStyles/withStyles.js:61:31)
    at TextField (webpack-internal:///./node_modules/@material-ui/core/esm/TextField/TextField.js:78:28)
    at WithStyles (webpack-internal:///./node_modules/@material-ui/styles/esm/withStyles/withStyles.js:61:31)
    at div
    at Downshift (webpack-internal:///./node_modules/downshift/dist/downshift.esm.js:449:28)
    at AutocompleteInput (webpack-internal:///./node_modules/ra-ui-materialui/esm/input/AutocompleteInput.js:162:28)
    at ListContextProvider (webpack-internal:///./node_modules/ra-core/esm/controller/ListContextProvider.js:41:20)
    at ResourceContextProvider (webpack-internal:///./node_modules/ra-core/esm/core/ResourceContextProvider.js:11:23)
    at ReferenceInputView (webpack-internal:///./node_modules/ra-ui-materialui/esm/input/ReferenceInput.js:159:25)
    at ReferenceInput (webpack-internal:///./node_modules/ra-ui-materialui/esm/input/ReferenceInput.js:119:21)
    at div
    at FormInput (webpack-internal:///./node_modules/ra-ui-materialui/esm/form/FormInput.js:46:23)
    at div
    at CardContent (webpack-internal:///./node_modules/@material-ui/core/esm/CardContent/CardContent.js:29:23)
    at WithStyles (webpack-internal:///./node_modules/@material-ui/styles/esm/withStyles/withStyles.js:61:31)
    at CardContentInner (webpack-internal:///./node_modules/ra-ui-materialui/esm/layout/CardContentInner.js:42:27)
    at form
    at SimpleFormView (webpack-internal:///./node_modules/ra-ui-materialui/esm/form/SimpleFormView.js:44:23)
    at FormView (webpack-internal:///./node_modules/ra-core/esm/form/FormWithRedirect.js:161:21)
    at ReactFinalForm (webpack-internal:///./node_modules/react-final-form/dist/react-final-form.es.js:164:20)
    at FormContextProvider (webpack-internal:///./node_modules/ra-core/esm/form/FormContextProvider.js:17:23)
    at FormWithRedirect (webpack-internal:///./node_modules/ra-core/esm/form/FormWithRedirect.js:76:20)
    at SimpleForm
    at div
    at Paper (webpack-internal:///./node_modules/@material-ui/core/esm/Paper/Paper.js:48:23)
    at WithStyles (webpack-internal:///./node_modules/@material-ui/styles/esm/withStyles/withStyles.js:61:31)
    at Card (webpack-internal:///./node_modules/@material-ui/core/esm/Card/Card.js:28:23)
    at WithStyles (webpack-internal:///./node_modules/@material-ui/styles/esm/withStyles/withStyles.js:61:31)
    at div
    at div
    at EditView (webpack-internal:///./node_modules/ra-ui-materialui/esm/detail/EditView.js:51:25)
    at RecordContextProvider (webpack-internal:///./node_modules/ra-core/esm/controller/RecordContext.js:31:23)
    at SaveContextProvider (webpack-internal:///./node_modules/ra-core/esm/controller/details/SaveContext.js:17:23)
    at EditContextProvider (webpack-internal:///./node_modules/ra-core/esm/controller/details/EditContextProvider.js:38:23)
    at ResourceContextProvider (webpack-internal:///./node_modules/ra-core/esm/core/ResourceContextProvider.js:11:23)
    at Edit (webpack-internal:///./node_modules/ra-ui-materialui/esm/detail/Edit.js:73:74)
    at WaitlistEdit
    at WithPermissions (webpack-internal:///./node_modules/ra-core/esm/auth/WithPermissions.js:69:25)
    at Route (webpack-internal:///./node_modules/react-router/esm/react-router.js:466:29)
    at Switch (webpack-internal:///./node_modules/react-router/esm/react-router.js:672:29)
    at ResourceContextProvider (webpack-internal:///./node_modules/ra-core/esm/core/ResourceContextProvider.js:11:23)
    at ResourceRoutes (webpack-internal:///./node_modules/ra-core/esm/core/Resource.js:57:19)
    at Resource (webpack-internal:///./node_modules/ra-core/esm/core/Resource.js:85:17)
    at Route (webpack-internal:///./node_modules/react-router/esm/react-router.js:466:29)
    at Switch (webpack-internal:///./node_modules/react-router/esm/react-router.js:672:29)
    at RoutesWithLayout (webpack-internal:///./node_modules/ra-core/esm/core/RoutesWithLayout.js:22:23)
    at div
    at main
    at div
    at div
    at LayoutWithoutTheme (webpack-internal:///./node_modules/ra-ui-materialui/esm/layout/Layout.js:124:28)
    at WithStyles (webpack-internal:///./node_modules/@material-ui/styles/esm/withStyles/withStyles.js:61:31)
    at C (webpack-internal:///./node_modules/react-router/esm/react-router.js:727:37)
    at ConnectFunction (webpack-internal:///./node_modules/react-redux/es/components/connectAdvanced.js:233:68)
    at ThemeProvider (webpack-internal:///./node_modules/@material-ui/styles/esm/ThemeProvider/ThemeProvider.js:42:24)
    at Layout (webpack-internal:///./node_modules/ra-ui-materialui/esm/layout/Layout.js:197:28)
    at Route (webpack-internal:///./node_modules/react-router/esm/react-router.js:466:29)
    at Switch (webpack-internal:///./node_modules/react-router/esm/react-router.js:672:29)
    at div
    at CoreAdminRouter (webpack-internal:///./node_modules/ra-core/esm/core/CoreAdminRouter.js:63:82)
    at Route (webpack-internal:///./node_modules/react-router/esm/react-router.js:466:29)
    at Switch (webpack-internal:///./node_modules/react-router/esm/react-router.js:672:29)
    at CoreAdminUI (webpack-internal:///./node_modules/ra-core/esm/core/CoreAdminUI.js:28:17)
    at AdminUI
    at Router (webpack-internal:///./node_modules/react-router/esm/react-router.js:95:30)
    at ConnectedRouter (webpack-internal:///./node_modules/connected-react-router/esm/ConnectedRouter.js:63:7)
    at ConnectedRouterWithContext (webpack-internal:///./node_modules/connected-react-router/esm/ConnectedRouter.js:187:25)
    at ConnectFunction (webpack-internal:///./node_modules/react-redux/es/components/connectAdvanced.js:233:68)
    at TranslationProvider (webpack-internal:///./node_modules/ra-core/esm/i18n/TranslationProvider.js:33:30)
    at Provider (webpack-internal:///./node_modules/react-redux/es/components/Provider.js:16:20)
    at CoreAdminContext (webpack-internal:///./node_modules/ra-core/esm/core/CoreAdminContext.js:21:27)
    at AdminContext
    at Admin (webpack-internal:///./node_modules/react-admin/esm/Admin.js:89:24)
    at ReactAdmin
    at LoadableComponent (webpack-internal:///./node_modules/next/dist/next-server/lib/loadable.js:188:37)
    at AdminPage
    at div
    at ClerkContextWrapper (webpack-internal:///./node_modules/@clerk/clerk-react/dist/clerk-react.esm.js:806:30)
    at ClerkProviderBase (webpack-internal:///./node_modules/@clerk/clerk-react/dist/clerk-react.esm.js:861:61)
    at Hoc (webpack-internal:///./node_modules/@clerk/clerk-react/dist/clerk-react.esm.js:161:5)
    at LeapApp (webpack-internal:///./pages/_app.tsx:67:24)
    at ErrorBoundary (webpack-internal:///./node_modules/@next/react-dev-overlay/lib/internal/ErrorBoundary.js:26:47)
    at ReactDevOverlay (webpack-internal:///./node_modules/@next/react-dev-overlay/lib/internal/ReactDevOverlay.js:86:23)
    at Container (webpack-internal:///./node_modules/next/dist/client/index.js:155:5)
    at AppContainer (webpack-internal:///./node_modules/next/dist/client/index.js:643:24)
    at Root (webpack-internal:///./node_modules/next/dist/client/index.js:779:25)
printWarning @ react-dom.development.js?61bb:67
error @ react-dom.development.js?61bb:43
updateWrapper @ react-dom.development.js?61bb:1539
updateProperties @ react-dom.development.js?61bb:9376
commitUpdate @ react-dom.development.js?61bb:10252
commitWork @ react-dom.development.js?61bb:21401
commitMutationEffects @ react-dom.development.js?61bb:23401
callCallback @ react-dom.development.js?61bb:3945
invokeGuardedCallbackDev @ react-dom.development.js?61bb:3994
invokeGuardedCallback @ react-dom.development.js?61bb:4056
commitRootImpl @ react-dom.development.js?61bb:23121
unstable_runWithPriority @ scheduler.development.js?3069:468
runWithPriority$1 @ react-dom.development.js?61bb:11276
commitRoot @ react-dom.development.js?61bb:22990
performSyncWorkOnRoot @ react-dom.development.js?61bb:22329
eval @ react-dom.development.js?61bb:11327
unstable_runWithPriority @ scheduler.development.js?3069:468
runWithPriority$1 @ react-dom.development.js?61bb:11276
flushSyncCallbackQueueImpl @ react-dom.development.js?61bb:11322
flushSyncCallbackQueue @ react-dom.development.js?61bb:11309
discreteUpdates$1 @ react-dom.development.js?61bb:22420
discreteUpdates @ react-dom.development.js?61bb:3756
dispatchDiscreteEvent @ react-dom.development.js?61bb:5889
downshift.esm.js?33ce:1581 downshift: A component has changed the controlled prop "inputValue" to be uncontrolled. This prop should not switch from controlled to uncontrolled (or vice versa). Decide between using a controlled or uncontrolled Downshift element for the lifetime of the component. More info: https://github.com/downshift-js/downshift#control-props
```

**Steps to reproduce:**
- Make a `SimpleForm` with `AutocompleteInput` inside a `ReferenceInput`.
- On load, the current value is not displayed. Only the label is displayed.
- On clicking into the input, the duplicate key error is displayed in console. In my case, the default suggestions included the current value also. Hence the duplicate key.

**Related code:**
```
<Edit {...props}>
        <SimpleForm redirect="show">
            <NumberField source="id" />
            <ReferenceInput source="topic_id" reference="topic">
                <AutocompleteInput optionText="name" resettable />
            </ReferenceInput>
        </SimpleForm>
    </Edit>
```

**Other information:**
- Stack traces ☝️ 

**Environment**
- Mac OS Big Sur
- Using React Admin inside a NextJS app with dynamic import of NextJS

* React-admin version: 3.16.2

* Last version that did not exhibit the issue (if applicable): First time user of React Admin
* React version: 17.0.2
* Browser: Chrome 91.0.4472.114
* Stack trace (in case of a JS error): See ☝️

**Comment by boks1971** [comment]
Screenshot of Edit view when it loads. The current `topic` is not shown
<img width="291" alt="Screenshot 2021-07-02 at 5 06 33 PM" src="https://user-images.githubusercontent.com/6278212/124269270-4d92bf80-db58-11eb-859d-559b94f06d59.png">

**Comment by djhi** [comment]
Thanks for reporting this. It seems to work fine on our simple example though. Can you please provide a sample application showing the issue by forking the following CodeSandbox (https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple)?

**Comment by boks1971** [comment]
Thank you @djhi Really appreciate it. Will look at providing an example.

In the mean time, I updated RA to 3.16.4 in my project and now I do not see any data :-( . Don't know what broke. Need to dig into that a bit.

**Comment by boks1971** [comment]
Sorry for the delay on this. Got tied up with other stuff.

Interestingly, I cannot reproduce this issue any more. I am on RA 3.17.0 now. Not sure if that had anything to do with it. Anyhow, glad it is not an issue any more. Closing. Thank you for your help.

**Comment by Tolfx** [comment]
I'm getting this error, and not being able to solve it, and I'm not sure what is the issue.
The version I'm using is:
```json
"react": "^17.0.2",
"react-admin": "^4.1.0",
"react-dom": "^17.0.2",
```

This is my setup code-wise.
React-Admin:
```tsx
...
<ReferenceInput  source="customer_uid" reference="customers">
  <AutocompleteInput
    isRequired={true}
    optionText={RenderFullName}
  />
</ReferenceInput>
...
```

The data is fetching from reference:
```json
[
  {
    "id": 1,
    "_id": "",
    "uid": "",
    "personal": {...},
    "billing": {...}
  }
]
```
Result when I'm editing it.
![image](https://user-images.githubusercontent.com/57797792/169322814-2d3ad304-da4c-44f8-af07-37c108b888bd.png)

It keeps being an issue when it comes to reference and Autocomplete.
First it doesn't show the default value on autocomplete but works fine if I would have used a `SelectInput`. Can't really wrap it with my head.

**Comment by slax57** [comment]
@Tolfx 
This issue does not seem related to #6408 , plus you are using a different react-admin version.
- If you think you have found an actual bug in the way react-admin handles ReferenceInput / AutocompleteInput , then please open a new Issue and provide a Codesandbox reproducing the problem with the simple example: https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple
- If you need support using these components, I suggest you ask your question on [stackoverflow](https://stackoverflow.com/questions/tagged/react-admin) , where you will find a much bigger community to help you
