### ISSUE TITLE
Invalid value for prop `refetch` on <div> tag.

### ISSUE THREAD

**Issue by davidhenley** [marmelab/react-admin#6428]
```
Warning: Invalid value for prop `refetch` on <div> tag. Either remove it from the element, or pass a string or number value to keep it in the DOM. For details, see https://reactjs.org/link/attribute-behavior 
    at div
    at ListView (http://localhost:3000/static/js/vendors~main.chunk.js:131473:23)
    at ListContextProvider (http://localhost:3000/static/js/vendors~main.chunk.js:48112:18)
    at List (http://localhost:3000/static/js/vendors~main.chunk.js:131056:79)
    at CustomerList
    at WithPermissions (http://localhost:3000/static/js/vendors~main.chunk.js:46449:23)
    at Route (http://localhost:3000/static/js/vendors~main.chunk.js:169896:29)
    at Switch (http://localhost:3000/static/js/vendors~main.chunk.js:170098:29)
    at ResourceContextProvider (http://localhost:3000/static/js/vendors~main.chunk.js:55372:21)
    at ResourceRoutes (http://localhost:3000/static/js/vendors~main.chunk.js:55238:17)
    at Resource (http://localhost:3000/static/js/vendors~main.chunk.js:55310:15)
    at Route (http://localhost:3000/static/js/vendors~main.chunk.js:169896:29)
    at Switch (http://localhost:3000/static/js/vendors~main.chunk.js:170098:29)
    at RoutesWithLayout (http://localhost:3000/static/js/vendors~main.chunk.js:55499:21)
    at div
    at main
    at div
    at div
    at LayoutWithoutTheme (http://localhost:3000/static/js/vendors~main.chunk.js:128890:24)
    at WithStyles (http://localhost:3000/static/js/vendors~main.chunk.js:6120:31)
    at C (http://localhost:3000/static/js/vendors~main.chunk.js:170153:37)
    at ConnectFunction (http://localhost:3000/static/js/vendors~main.chunk.js:167003:75)
    at ThemeProvider (http://localhost:3000/static/js/vendors~main.chunk.js:4822:24)
    at Layout (http://localhost:3000/static/js/vendors~main.chunk.js:129008:26)
    at Route (http://localhost:3000/static/js/vendors~main.chunk.js:169896:29)
    at Switch (http://localhost:3000/static/js/vendors~main.chunk.js:170098:29)
    at div
    at CoreAdminRouter (http://localhost:3000/static/js/vendors~main.chunk.js:54874:87)
    at Route (http://localhost:3000/static/js/vendors~main.chunk.js:169896:29)
    at Switch (http://localhost:3000/static/js/vendors~main.chunk.js:170098:29)
    at CoreAdminUI (http://localhost:3000/static/js/vendors~main.chunk.js:55090:15)
    at AdminUI
    at Router (http://localhost:3000/static/js/vendors~main.chunk.js:169531:30)
    at ConnectedRouter (http://localhost:3000/static/js/vendors~main.chunk.js:14113:7)
    at ConnectedRouterWithContext (http://localhost:3000/static/js/vendors~main.chunk.js:14236:25)
    at ConnectFunction (http://localhost:3000/static/js/vendors~main.chunk.js:167003:75)
    at TranslationProvider (http://localhost:3000/static/js/vendors~main.chunk.js:63882:28)
    at Provider (http://localhost:3000/static/js/vendors~main.chunk.js:166716:20)
    at CoreAdminContext (http://localhost:3000/static/js/vendors~main.chunk.js:54637:25)
    at AdminContext
    at Admin (http://localhost:3000/static/js/vendors~main.chunk.js:71741:22)
    at App
```

**Comment by djhi** [comment]
Please follow the issue template

**Comment by ryanmstokes** [comment]
Hi @davidhenley - Did you find a solution to fix this warning?
