### ISSUE TITLE
jest test: TypeError: Cannot read properties of null (reading 'breakpoints')

### ISSUE THREAD

**Issue by gianiaz** [marmelab/react-admin#6647]
I have this behaviour in a test, I've over-simplified for example purpose (in my real world use case I need the context for rendering) :

`/src/MyButton.tsx`
```
import { Button } from 'react-admin'
export const MyButton = () => <Button label="Testing purpose" disabled={true}></Button>
```

It's test
`/test/MyButton.test.tsx`
```
import { render } from '@testing-library/react'
import { TestContext } from 'ra-test'
import React from 'react'
import { MyButton } from '../src/MyButton.tsx' 

describe('My Button', () => {
    it('should show a disabled button', () => {
        const result = render(
            <TestContext>
                <MyButtonField />
            </TestContext>
        )
        const mybutton = screen.getByText('Testing Purpose')
        expect(mybutton?.closest('button')).toBeDisabled()
     }
);
```

**Environment**

* React-admin version: 3.17.3
* Last version that did not exhibit the issue (if applicable): N.A.
* React version: 17.0.2
* Browser: Jest
* Stack trace (in case of a JS error):
```
TypeError: Cannot read properties of null (reading 'breakpoints')

      22 | describe('MyButton', () => {
      23 |     it('should show a disabled button', () => {
    > 24 |         const result = render(
         |                              ^
      25 |             <TestContext>
      26 |                 <MyButton />
      27 |             </TestContext>


      at node_modules/ra-ui-materialui/lib/button/Button.js:73:22
      at Object.useMediaQuery (node_modules/@material-ui/core/useMediaQuery/useMediaQuery.js:33:50)
      at Button (node_modules/ra-ui-materialui/lib/button/Button.js:72:27)
      at renderWithHooks (node_modules/react-dom/cjs/react-dom.development.js:14985:18)
      at mountIndeterminateComponent (node_modules/react-dom/cjs/react-dom.development.js:17811:13)
      at beginWork (node_modules/react-dom/cjs/react-dom.development.js:19049:16)
      at HTMLUnknownElement.callCallback (node_modules/react-dom/cjs/react-dom.development.js:3945:14)
      at HTMLUnknownElement.callTheUserObjectsOperation (node_modules/jsdom/lib/jsdom/living/generated/EventListener.js:26:30)
      at innerInvokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:338:25)
      at invokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:274:3)
      at HTMLUnknownElementImpl._dispatch (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:221:9)
      at HTMLUnknownElementImpl.dispatchEvent (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:94:17)
      at HTMLUnknownElement.dispatchEvent (node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:231:34)
      at Object.invokeGuardedCallbackDev (node_modules/react-dom/cjs/react-dom.development.js:3994:16)
      at invokeGuardedCallback (node_modules/react-dom/cjs/react-dom.development.js:4056:31)
      at beginWork$1 (node_modules/react-dom/cjs/react-dom.development.js:23964:7)
      at performUnitOfWork (node_modules/react-dom/cjs/react-dom.development.js:22779:12)
      at workLoopSync (node_modules/react-dom/cjs/react-dom.development.js:22707:5)
      at renderRootSync (node_modules/react-dom/cjs/react-dom.development.js:22670:7)
      at performSyncWorkOnRoot (node_modules/react-dom/cjs/react-dom.development.js:22293:18)
      at scheduleUpdateOnFiber (node_modules/react-dom/cjs/react-dom.development.js:21881:7)
      at updateContainer (node_modules/react-dom/cjs/react-dom.development.js:25482:3)
      at node_modules/react-dom/cjs/react-dom.development.js:26021:7
      at unbatchedUpdates (node_modules/react-dom/cjs/react-dom.development.js:22431:12)
      at legacyRenderSubtreeIntoContainer (node_modules/react-dom/cjs/react-dom.development.js:26020:5)
      at Object.render (node_modules/react-dom/cjs/react-dom.development.js:26103:10)
      at node_modules/@testing-library/react/dist/pure.js:101:25
      at batchedUpdates$1 (node_modules/react-dom/cjs/react-dom.development.js:22380:12)
      at act (node_modules/react-dom/cjs/react-dom-test-utils.development.js:1042:14)
      at render (node_modules/@testing-library/react/dist/pure.js:97:26)
      at Object.<anonymous> (tests/MyButton.test.tsx:24:30)
      at TestScheduler.scheduleTests (node_modules/@jest/core/build/TestScheduler.js:333:13)
      at runJest (node_modules/@jest/core/build/runJest.js:387:19)
      at _run10000 (node_modules/@jest/core/build/cli/index.js:408:7)
      at runCLI (node_modules/@jest/core/build/cli/index.js:261:3)
```

**Comment by djhi** [comment]
You are most probably using react-admin `<Button>` component which need the `ThemeProvider` from mui.
Wrap the content you send to `render` inside a `<ThemeProvider theme={createMuiTheme()}>` and it should work
