### ISSUE TITLE
Array Input not working as described

### ISSUE THREAD

**Issue by evergreen-trading-systems** [marmelab/react-admin#7088]
```js
<ArrayInput source="authors">
    <SimpleFormIterator>
        <DateInput source="user" />
        <TextInput source="role" />
    </SimpleFormIterator>
</ArrayInput>
```

Does not work https://marmelab.com/react-admin/Inputs.html#arrayinput

**What you were expecting:**
https://marmelab.com/react-admin/Inputs.html#arrayinput

**What happened instead:**
```
react-final-form.es.js:296 Uncaught Error: useFieldArray must be used inside of a <Form> component
    at useForm (react-final-form.es.js:296)
    at useFieldArray (react-final-form-arrays.es.js:79)
    at ArrayInput (ArrayInput.js:80)
    at renderWithHooks (react-dom.development.js:14985)
    at mountIndeterminateComponent (react-dom.development.js:17811)
    at beginWork (react-dom.development.js:19049)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3945)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994)
    at invokeGuardedCallback (react-dom.development.js:4056)
    at beginWork$1 (react-dom.development.js:23964)
```

**Steps to reproduce:**
```js
const DoesNotWork = () => {
  return (
        <ArrayInput source="authors">
            <SimpleFormIterator>
                <TextInput source="role" />
            </SimpleFormIterator>
        </ArrayInput>
    )
}
```

**Other information:**

**Environment**

* React-admin version: latest
* Last version that did not exhibit the issue (if applicable):
* React version: latest
* Browser: chrome
* Stack trace (in case of a JS error):
```
react-final-form.es.js:296 Uncaught Error: useFieldArray must be used inside of a <Form> component
    at useForm (react-final-form.es.js:296)
    at useFieldArray (react-final-form-arrays.es.js:79)
    at ArrayInput (ArrayInput.js:80)
    at renderWithHooks (react-dom.development.js:14985)
    at mountIndeterminateComponent (react-dom.development.js:17811)
    at beginWork (react-dom.development.js:19049)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3945)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994)
    at invokeGuardedCallback (react-dom.development.js:4056)
    at beginWork$1 (react-dom.development.js:23964)
useForm @ react-final-form.es.js:296
useFieldArray @ react-final-form-arrays.es.js:79
ArrayInput @ ArrayInput.js:80
renderWithHooks @ react-dom.development.js:14985
mountIndeterminateComponent @ react-dom.development.js:17811
beginWork @ react-dom.development.js:19049
callCallback @ react-dom.development.js:3945
invokeGuardedCallbackDev @ react-dom.development.js:3994
invokeGuardedCallback @ react-dom.development.js:4056
beginWork$1 @ react-dom.development.js:23964
performUnitOfWork @ react-dom.development.js:22776
workLoopSync @ react-dom.development.js:22707
renderRootSync @ react-dom.development.js:22670
performSyncWorkOnRoot @ react-dom.development.js:22293
(anonymous) @ react-dom.development.js:11327
unstable_runWithPriority @ scheduler.development.js:468
runWithPriority$1 @ react-dom.development.js:11276
flushSyncCallbackQueueImpl @ react-dom.development.js:11322
flushSyncCallbackQueue @ react-dom.development.js:11309
unbatchedUpdates @ react-dom.development.js:22438
legacyRenderSubtreeIntoContainer @ react-dom.development.js:26020
render @ react-dom.development.js:26103
./src/index.tsx @ index.tsx:7
options.factory @ react refresh:6
__webpack_require__ @ bootstrap:24
(anonymous) @ startup:7
(anonymous) @ startup:7
react-dom.development.js:20085 The above error occurred in the <ArrayInput> component:

    at ArrayInput (http://localhost:3000/static/js/bundle.js:121156:25)
    at YourElectedParties (http://localhost:3000/static/js/bundle.js:1208:98)
    at WithPermissions (http://localhost:3000/static/js/bundle.js:97072:26)
    at Route (http://localhost:3000/static/js/bundle.js:160942:29)
    at Switch (http://localhost:3000/static/js/bundle.js:161144:29)
    at ResourceContextProvider (http://localhost:3000/static/js/bundle.js:102760:21)
    at ResourceRoutes (http://localhost:3000/static/js/bundle.js:102626:20)
    at Resource (http://localhost:3000/static/js/bundle.js:102698:18)
    at Route (http://localhost:3000/static/js/bundle.js:160942:29)
    at Switch (http://localhost:3000/static/js/bundle.js:161144:29)
    at RoutesWithLayout (http://localhost:3000/static/js/bundle.js:102805:24)
    at div
    at main
    at div
    at div
    at LayoutWithoutTheme (http://localhost:3000/static/js/bundle.js:124294:24)
    at WithStyles (http://localhost:3000/static/js/bundle.js:27278:31)
    at C (http://localhost:3000/static/js/bundle.js:161199:37)
    at ConnectFunction (http://localhost:3000/static/js/bundle.js:157987:68)
    at ThemeProvider (http://localhost:3000/static/js/bundle.js:26423:24)
    at Layout (http://localhost:3000/static/js/bundle.js:124412:26)
    at Route (http://localhost:3000/static/js/bundle.js:160942:29)
    at Switch (http://localhost:3000/static/js/bundle.js:161144:29)
    at div
    at CoreAdminRouter (http://localhost:3000/static/js/bundle.js:102260:73)
    at Route (http://localhost:3000/static/js/bundle.js:160942:29)
    at Switch (http://localhost:3000/static/js/bundle.js:161144:29)
    at CoreAdminUI (http://localhost:3000/static/js/bundle.js:102477:18)
    at AdminUI
    at Router (http://localhost:3000/static/js/bundle.js:160573:30)
    at ConnectedRouter (http://localhost:3000/static/js/bundle.js:54238:7)
    at ConnectedRouterWithContext (http://localhost:3000/static/js/bundle.js:54361:25)
    at ConnectFunction (http://localhost:3000/static/js/bundle.js:157987:68)
    at TranslationProvider (http://localhost:3000/static/js/bundle.js:108882:28)
    at Provider (http://localhost:3000/static/js/bundle.js:157699:20)
    at CoreAdminContext (http://localhost:3000/static/js/bundle.js:102020:28)
    at AdminContext
    at Admin (http://localhost:3000/static/js/bundle.js:130127:25)
    at App

React will try to recreate this component tree from scratch using the error boundary you provided, LayoutWithoutTheme.
```

**Comment by fzaninotto** [comment]
It seems the error message is explicit enough: you must use it in a form component (`<SimpleForm>` or `<TabbedForm>`).

If you did, please provide a link to a CodeSandbox demonstrating the issue.

**Comment by WiXSL** [comment]
This sound like a typical misused of the component, just like @fzaninotto described.
I'm closing this issue. But please, if you can provide a code-sandbox reproducing the issue, feel free to re-open this issue at any time.
