### ISSUE TITLE
Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application.

### ISSUE THREAD

**Issue by neutron92** [marmelab/react-admin#7147]
**What you were expecting:**
I'm in a create page contains SimpleForm with some inputs and a reference input and i want to navigate to an other page by clicking in the menu or any other link

**What happened instead:**
i got this error in console
`Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application.`
Caused by the input refrence
![image](https://user-images.githubusercontent.com/6135555/151288665-02f720cc-0a96-47b7-81c7-fd2e85b9e252.png)

**Steps to reproduce:**
Click in the ReferenceInput with or without selecting any option then change the page via the menu in the topbar or sidebar

**Related code:**
![image](https://user-images.githubusercontent.com/6135555/151288614-7773c028-d40b-4633-b188-da65f2bc54e1.png)
![image](https://user-images.githubusercontent.com/6135555/151288636-c2c23a35-df41-46b8-a147-0b61c71a9fcf.png)

```
export const LanguagesInput = (props: any) => {
  return (
    <ReferenceArrayInput
      source={props.source}
      reference={props.reference}
      >
        <AutocompleteArrayInput optionValue="id" optionText="locale" allowEmpty={false}/>
    </ReferenceArrayInput>
  );
};
```

```
<LanguagesInput
   source="languagesIds"
  reference="languages"
></LanguagesInput>
```
**Environment**

* React-admin version: 3.19.7
* React version: 17.0.2
* Browser: chrome
* Stack trace (in case of a JS error):
```

Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
    at ReferenceArrayInput (http://localhost:3000/static/js/bundle.js:126452:21)
    at LanguagesInput (http://localhost:3000/static/js/bundle.js:300:19)
    at div
    at FormInput (http://localhost:3000/static/js/bundle.js:123900:21)
    at div
    at CardContent (http://localhost:3000/static/js/bundle.js:6796:23)
    at WithStyles (http://localhost:3000/static/js/bundle.js:31334:31)
    at CardContentInner (http://localhost:3000/static/js/bundle.js:128366:25)
    at form
    at SimpleFormView (http://localhost:3000/static/js/bundle.js:124088:21)
    at FormView (http://localhost:3000/static/js/bundle.js:109805:29)
    at ReactFinalForm (http://localhost:3000/static/js/bundle.js:160931:20)
    at FormContextProvider (http://localhost:3000/static/js/bundle.js:109219:21)
    at RecordContextProvider (http://localhost:3000/static/js/bundle.js:96302:21)
    at FormWithRedirect (http://localhost:3000/static/js/bundle.js:109655:18)
    at SimpleForm
    at div
    at Paper (http://localhost:3000/static/js/bundle.js:17388:23)
    at WithStyles (http://localhost:3000/static/js/bundle.js:31334:31)
    at Card (http://localhost:3000/static/js/bundle.js:6631:23)
    at WithStyles (http://localhost:3000/static/js/bundle.js:31334:31)
    at div
    at div
    at CreateView (http://localhost:3000/static/js/bundle.js:122611:23)
    at RecordContextProvider (http://localhost:3000/static/js/bundle.js:96302:21)
    at SaveContextProvider (http://localhost:3000/static/js/bundle.js:97234:21)
    at CreateContextProvider (http://localhost:3000/static/js/bundle.js:96881:21)
    at ResourceContextProvider (http://localhost:3000/static/js/bundle.js:103245:21)
    at Create (http://localhost:3000/static/js/bundle.js:122523:72)
    at CountryCreate
    at WithPermissions (http://localhost:3000/static/js/bundle.js:94298:26)
    at Route (http://localhost:3000/static/js/bundle.js:165311:29)
    at Switch (http://localhost:3000/static/js/bundle.js:165513:29)
    at ResourceContextProvider (http://localhost:3000/static/js/bundle.js:103245:21)
    at ResourceRoutes (http://localhost:3000/static/js/bundle.js:103111:20)
    at Resource (http://localhost:3000/static/js/bundle.js:103183:18)
    at Route (http://localhost:3000/static/js/bundle.js:165311:29)
```

**Comment by djhi** [comment]
Please follow the issue template

**Comment by neutron92** [comment]
@djhi done

**Comment by neutron92** [comment]
@djhi 
https://codesandbox.io/s/new-cherry-u53rk?file=/src/comments/PostReferenceInput.tsx

My changes are here `PostReferenceInput.tsx`


how you can reproduce it:
- go to create a comment page  click in the posts section Juste let it list for you the available posts of the list
![image](https://user-images.githubusercontent.com/6135555/151389716-eb2377dc-a7af-40d8-8c64-a6be7753c22a.png)
- then without try to change the page by clicking in the sidebar menu 
![image](https://user-images.githubusercontent.com/6135555/151389919-447882b1-d6ad-47a1-9c14-4f09537ba97e.png)

and you will see the error
![image](https://user-images.githubusercontent.com/6135555/151389998-c8896bd4-8286-4173-b3f8-d7e6a609519a.png)

**Comment by djhi** [comment]
Thanks for the report! We'll look into it

**Comment by WiXSL** [comment]
Strange, I could'n reproduce it in your codesandbox.

![Captura de pantalla 2022-01-31 093308](https://user-images.githubusercontent.com/8268610/151794562-8be27eca-2ee7-40fe-baa8-1e004f1cc034.png)
