### ISSUE TITLE
demo example not working for graphql

### ISSUE THREAD

**Issue by DVGY** [marmelab/react-admin#7310]
**What you were expecting:**

I was expecting it fetch order and prices as it was doing using fakerest

**What happened instead:**

When api is switched to graphql it return apollo error
**Steps to reproduce:**

Pls run the code in demo folder and inside  App.tsx replace `process.env.REACT_APP_DATA_PROVIDER` with graphql

**Related code:**

<img width="1127" alt="image" src="https://user-images.githubusercontent.com/46158826/155828374-3b83dd95-bbcd-4e59-adcb-829f145365cc.png">

**Environment**

* React-admin version:  : "^3.9.0",

* Last version that did not exhibit the issue (if applicable):
* React version: : "^17.0.0",
* Browser: Chrome
* Stack trace (in case of a JS error):
```
Error: Unexpected end of JSON input
    at new ApolloError (index.ts:58:1)
    at QueryManager.ts:1067:1
    at both (asyncMap.ts:30:1)
    at asyncMap.ts:19:1
    at new Promise (<anonymous>)
    at Object.then (asyncMap.ts:19:1)
    at Object.error (asyncMap.ts:31:1)
    at notifySubscription (module.js:137:1)
    at onNotify (module.js:176:1)
    at SubscriptionObserver.error (module.js:229:1)
overrideMethod @ react_devtools_backend.js:4061
(anonymous) @ performPessimisticQuery.js:56
Promise.catch (async)
performPessimisticQuery @ performPessimisticQuery.js:53
doQuery @ doQuery.js:59
(anonymous) @ useDataProvider.js:188
(anonymous) @ useQueryWithStore.js:196
(anonymous) @ useQueryWithStore.js:195
invokePassiveEffectCreate @ react-dom.development.js:23487
callCallback @ react-dom.development.js:3945
invokeGuardedCallbackDev @ react-dom.development.js:3994
invokeGuardedCallback @ react-dom.development.js:4056
flushPassiveEffectsImpl @ react-dom.development.js:23574
unstable_runWithPriority @ scheduler.development.js:468
runWithPriority$1 @ react-dom.development.js:11276
flushPassiveEffects @ react-dom.development.js:23447
performSyncWorkOnRoot @ react-dom.development.js:22269
(anonymous) @ react-dom.development.js:11327
unstable_runWithPriority @ scheduler.development.js:468
runWithPriority$1 @ react-dom.development.js:11276
flushSyncCallbackQueueImpl @ react-dom.development.js:11322
flushSyncCallbackQueue @ react-dom.development.js:11309
scheduleUpdateOnFiber @ react-dom.development.js:21893
dispatchAction @ react-dom.development.js:16139
(anonymous) @ hooks.js:15
(anonymous) @ useGetIdentity.js:91
step @ useGetIdentity.js:32
(anonymous) @ useGetIdentity.js:13
fulfilled @ useGetIdentity.js:4
Promise.then (async)
step @ useGetIdentity.js:6
(anonymous) @ useGetIdentity.js:7
__webpack_modules__../node_modules/ra-core/esm/auth/useGetIdentity.js.__awaiter @ useGetIdentity.js:3
callAuthProvider @ useGetIdentity.js:82
(anonymous) @ useGetIdentity.js:109
invokePassiveEffectCreate @ react-dom.development.js:23487
callCallback @ react-dom.development.js:3945
invokeGuardedCallbackDev @ react-dom.development.js:3994
invokeGuardedCallback @ react-dom.development.js:4056
flushPassiveEffectsImpl @ react-dom.development.js:23574
unstable_runWithPriority @ scheduler.development.js:468
runWithPriority$1 @ react-dom.development.js:11276
flushPassiveEffects @ react-dom.development.js:23447
performSyncWorkOnRoot @ react-dom.development.js:22269
(anonymous) @ react-dom.development.js:11327
unstable_runWithPriority @ scheduler.development.js:468
runWithPriority$1 @ react-dom.development.js:11276
flushSyncCallbackQueueImpl @ react-dom.development.js:11322
flushSyncCallbackQueue @ react-dom.development.js:11309
unbatchedUpdates @ react-dom.development.js:22438
legacyRenderSubtreeIntoContainer @ react-dom.development.js:26020
render @ react-dom.development.js:26103
./src/index.tsx @ index.tsx:13
options.factory @ react refresh:6
__webpack_require__ @ bootstrap:24
(anonymous) @ startup:7
(anonymous) @ startup:7
```

**Comment by fzaninotto** [comment]
I can't replicate on a checkout of the `master` branch after running:

```
make install
make build
make run-graphql-demo
```

Can you please check again?

**Comment by DVGY** [comment]
@fzaninotto it's running now. I will close this issue
