### ISSUE TITLE
Validation resolvers don't work

### ISSUE THREAD

**Issue by andrico1234** [marmelab/react-admin#7333]
**What you were expecting:**
Form validation based on the `yup` schema.
Error messages to display at the correct places

**What happened instead:**
Errors in the console, and no validation

```
ncaught (in promise) TypeError: e is not a function
    at _callee13$ (getSimpleValidationResolver.ts:25:1)
    at tryCatch (runtime.js:63:1)
    at Generator.invoke [as _invoke] (runtime.js:294:1)
    at Generator.next (runtime.js:119:1)
    at asyncGeneratorStep (asyncToGenerator.js:3:1)
    at _next (asyncToGenerator.js:25:1)
    at asyncToGenerator.js:32:1
    at new Promise (<anonymous>)
    at Object.<anonymous> (asyncToGenerator.js:21:1)
    at Object.resolver (getSimpleValidationResolver.ts:25:1)
```

**Related code:**

* Preferably, a CodeSandbox forked from https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple
* A link to a GitHub repo with the minimal codebase to reproduce the issue

```
insert short code snippets here
```

**Other information:**

**Environment**

* React-admin version:
* Last version that did not exhibit the issue (if applicable):
* React version:
* Browser:
* Stack trace (in case of a JS error):

**Comment by andrico1234** [comment]
I tried creating this issue in the codesandbox, but after installing `yup` the project couldn't compile

**Comment by andrico1234** [comment]
https://github.com/marmelab/react-admin/pull/7335

I thought I created a link to a repro case but I didn't! 🤦🏽‍♂️ my bad

**Comment by andrico1234** [comment]
Just bumping this, is there anything else I can provide? Or an alternative approach you suggest when it comes to form validation?

**Comment by djhi** [comment]
Thanks for the reproduction. We'll do our best to investigate but we currently have more important issues.

**Comment by WiXSL** [comment]
Reproduced. Thanks for the report
