### ISSUE TITLE
missing jsonexport package

### ISSUE THREAD

**Issue by tupe12334** [marmelab/react-admin#7396]
**What you were expecting:**
I tried to run the tests of the ra-data-graphql-simple package after I added the correct types and the test crashed on missing jsonexport/dist package 
```
> jest

 PASS  src/getFinalType.test.ts
 PASS  src/isRequired.test.ts
 PASS  src/isList.test.ts
 FAIL  src/getResponseParser.test.ts
  ● Test suite failed to run

    Cannot find module 'jsonexport/dist' from 'node_modules/ra-core/lib/export/defaultExporter.js'

    Require stack:
      node_modules/ra-core/lib/export/defaultExporter.js
      node_modules/ra-core/lib/controller/useListController.js
      node_modules/ra-core/lib/controller/ListController.js
      node_modules/ra-core/lib/controller/index.js
      node_modules/ra-core/lib/dataProvider/useGetMany.js
      node_modules/ra-core/lib/dataProvider/index.js
      node_modules/ra-core/lib/core/CoreAdminContext.js
      node_modules/ra-core/lib/core/CoreAdmin.js
      node_modules/ra-core/lib/core/components.js
      node_modules/ra-core/lib/core/index.js
      node_modules/ra-core/lib/actions/dataActions/crudCreate.js
      node_modules/ra-core/lib/actions/dataActions/index.js
      node_modules/ra-core/lib/actions/accumulateActions.js
      node_modules/ra-core/lib/actions/index.js
      node_modules/ra-core/lib/reducer/admin/resource/index.js
      node_modules/ra-core/lib/reducer/admin/index.js
      node_modules/ra-core/lib/reducer/index.js
      node_modules/ra-core/lib/index.js
      src/getResponseParser.test.ts

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:306:11)
      at Object.<anonymous> (node_modules/ra-core/lib/export/defaultExporter.js:6:30)

 FAIL  src/buildQuery.test.ts
  ● Test suite failed to run

    Cannot find module 'jsonexport/dist' from 'node_modules/ra-core/lib/export/defaultExporter.js'

    Require stack:
      node_modules/ra-core/lib/export/defaultExporter.js
      node_modules/ra-core/lib/controller/useListController.js
      node_modules/ra-core/lib/controller/ListController.js
      node_modules/ra-core/lib/controller/index.js
      node_modules/ra-core/lib/dataProvider/useGetMany.js
      node_modules/ra-core/lib/dataProvider/index.js
      node_modules/ra-core/lib/core/CoreAdminContext.js
      node_modules/ra-core/lib/core/CoreAdmin.js
      node_modules/ra-core/lib/core/components.js
      node_modules/ra-core/lib/core/index.js
      node_modules/ra-core/lib/actions/dataActions/crudCreate.js
      node_modules/ra-core/lib/actions/dataActions/index.js
      node_modules/ra-core/lib/actions/accumulateActions.js
      node_modules/ra-core/lib/actions/index.js
      node_modules/ra-core/lib/reducer/admin/resource/index.js
      node_modules/ra-core/lib/reducer/admin/index.js
      node_modules/ra-core/lib/reducer/index.js
      node_modules/ra-core/lib/index.js
      src/buildQuery.test.ts

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:306:11)
      at Object.<anonymous> (node_modules/ra-core/lib/export/defaultExporter.js:6:30)

 FAIL  src/buildGqlQuery.test.ts
  ● Test suite failed to run

    Cannot find module 'jsonexport/dist' from 'node_modules/ra-core/lib/export/defaultExporter.js'

    Require stack:
      node_modules/ra-core/lib/export/defaultExporter.js
      node_modules/ra-core/lib/controller/useListController.js
      node_modules/ra-core/lib/controller/ListController.js
      node_modules/ra-core/lib/controller/index.js
      node_modules/ra-core/lib/dataProvider/useGetMany.js
      node_modules/ra-core/lib/dataProvider/index.js
      node_modules/ra-core/lib/core/CoreAdminContext.js
      node_modules/ra-core/lib/core/CoreAdmin.js
      node_modules/ra-core/lib/core/components.js
      node_modules/ra-core/lib/core/index.js
      node_modules/ra-core/lib/actions/dataActions/crudCreate.js
      node_modules/ra-core/lib/actions/dataActions/index.js
      node_modules/ra-core/lib/actions/accumulateActions.js
      node_modules/ra-core/lib/actions/index.js
      node_modules/ra-core/lib/reducer/admin/resource/index.js
      node_modules/ra-core/lib/reducer/admin/index.js
      node_modules/ra-core/lib/reducer/index.js
      node_modules/ra-core/lib/index.js
      src/buildGqlQuery.test.ts

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:306:11)
      at Object.<anonymous> (node_modules/ra-core/lib/export/defaultExporter.js:6:30)

 FAIL  src/buildVariables.test.ts
  ● Test suite failed to run

    Cannot find module 'jsonexport/dist' from 'node_modules/ra-core/lib/export/defaultExporter.js'

    Require stack:
      node_modules/ra-core/lib/export/defaultExporter.js
      node_modules/ra-core/lib/controller/useListController.js
      node_modules/ra-core/lib/controller/ListController.js
      node_modules/ra-core/lib/controller/index.js
      node_modules/ra-core/lib/dataProvider/useGetMany.js
      node_modules/ra-core/lib/dataProvider/index.js
      node_modules/ra-core/lib/core/CoreAdminContext.js
      node_modules/ra-core/lib/core/CoreAdmin.js
      node_modules/ra-core/lib/core/components.js
      node_modules/ra-core/lib/core/index.js
      node_modules/ra-core/lib/actions/dataActions/crudCreate.js
      node_modules/ra-core/lib/actions/dataActions/index.js
      node_modules/ra-core/lib/actions/accumulateActions.js
      node_modules/ra-core/lib/actions/index.js
      node_modules/ra-core/lib/reducer/admin/resource/index.js
      node_modules/ra-core/lib/reducer/admin/index.js
      node_modules/ra-core/lib/reducer/index.js
      node_modules/ra-core/lib/index.js
      src/buildVariables.test.ts

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:306:11)
      at Object.<anonymous> (node_modules/ra-core/lib/export/defaultExporter.js:6:30)

Test Suites: 4 failed, 3 passed, 7 total
Tests:       12 passed, 12 total
Snapshots:   0 total
Time:        1.454 s
Ran all test suites.
The terminal process "/bin/zsh '-c', 'npm run test'" terminated with exit code: 1.
```

**Steps to reproduce:**
open the commit that I attracted below -> run npm I -> run the tests

**Related code:**
https://github.com/amplication/ra-data-graphql-amplication/tree/056914117efa729f1f960cd1767952858282cae9

**Comment by fzaninotto** [comment]
The tests run on GitHub, and in our local checkouts. Please use the `make` commands to install the project, as explained in the README.

**Comment by jvert** [comment]
I hit a similar problem and found a few packages (jsonexport and final-form-arrays) which were referenced by ra-core, but the dependency is actually declared in a different package. So, if you are depending solely on ra-core, it is not going to work. Either add those dependencies explicitly, or depend on the full react-admin package

**Comment by fzaninotto** [comment]
No news for some time, closing.
