### ISSUE TITLE
Migration react-admin v3 to v4 infinite loop with resources

### ISSUE THREAD

**Issue by jeanjs** [marmelab/react-admin#7760]
After migrating my application to v4,  following the docs recommendations my resources for some reason it gets stuck in a loop and this is the console warning:

Maximum update depth exceeded. This can happen when a component calls setState inside useEffect, but useEffect either doesn't have a dependency array, or one of the dependencies changes on every render.
    at CoreAdminRoutes (http://v3.ecglobal.local:3000/static/js/vendors.two.chunk.js:93529:11)
    at Routes (http://v3.ecglobal.local:3000/static/js/vendors.two.chunk.js:156922:5)
    at CoreAdminUI (http://v3.ecglobal.local:3000/static/js/vendors.two.chunk.js:93603:15)
    at AdminUI (http://v3.ecglobal.local:3000/static/js/vendors.two.chunk.js:113365:19)
    at InnerThemeProvider (http://v3.ecglobal.local:3000/static/js/vendors.three.chunk.js:259977:74)
    at ThemeProvider (http://v3.ecglobal.local:3000/static/js/vendors.three.chunk.js:259212:5)
    at ThemeProvider (http://v3.ecglobal.local:3000/static/js/vendors.three.chunk.js:259997:5)
    at ThemeProvider (http://v3.ecglobal.local:3000/static/js/vendors.two.chunk.js:104250:15)
    at ResourceDefinitionContextProvider (http://v3.ecglobal.local:3000/static/js/vendors.two.chunk.js:93350:18)
    at NotificationContextProvider (http://v3.ecglobal.local:3000/static/js/vendors.two.chunk.js:91057:15)
    at I18nContextProvider (http://v3.ecglobal.local:3000/static/js/vendors.two.chunk.js:91082:12)
    at DummyRouter (http://v3.ecglobal.local:3000/static/js/vendors.two.chunk.js:90661:15)
    at BasenameContextProvider (http://v3.ecglobal.local:3000/static/js/vendors.two.chunk.js:90638:15)
    at AdminRouter (http://v3.ecglobal.local:3000/static/js/vendors.two.chunk.js:90647:14)
    at QueryClientProvider (http://v3.ecglobal.local:3000/static/js/vendors.two.chunk.js:150835:21)
    at StoreContextProvider (http://v3.ecglobal.local:3000/static/js/vendors.two.chunk.js:90984:12)
    at CoreAdminContext (http://v3.ecglobal.local:3000/static/js/vendors.two.chunk.js:93380:19)
    at AdminContext (http://v3.ecglobal.local:3000/static/js/vendors.two.chunk.js:113383:12)
    at Admin (http://v3.ecglobal.local:3000/static/js/vendors.one.chunk.js:107397:19)
    at AdminScreen (http://v3.ecglobal.local:3000/static/js/admin.chunk.js:38049:89)
    at AdminContextProvider (http://v3.ecglobal.local:3000/static/js/admin.chunk.js:29398:5)
    at PrivateRoute (http://v3.ecglobal.local:3000/static/js/main.chunk.js:708:5)
    at Routes (http://v3.ecglobal.local:3000/static/js/vendors.two.chunk.js:156922:5)
    at Suspense
    at Router (http://v3.ecglobal.local:3000/static/js/vendors.two.chunk.js:156855:15)
    at BrowserRouter (http://v3.ecglobal.local:3000/static/js/vendors.two.chunk.js:155662:5)
    at PreviewCardProvider (http://v3.ecglobal.local:3000/static/js/main.chunk.js:31210:5)
    at ThemeProvider (http://v3.ecglobal.local:3000/static/js/vendors.one.chunk.js:155902:76)
    at AppRouters (http://v3.ecglobal.local:3000/static/js/main.chunk.js:17642:74)
    at NotificationProvider (http://v3.ecglobal.local:3000/static/js/main.chunk.js:27330:5)
    at ImageGridLightBoxProvider (http://v3.ecglobal.local:3000/static/js/main.chunk.js:12429:5)
    at AuthProvider (http://v3.ecglobal.local:3000/static/js/main.chunk.js:1816:5)
    at GlobalDataProvider (http://v3.ecglobal.local:3000/static/js/main.chunk.js:39319:5)
    at ApolloProvider (http://v3.ecglobal.local:3000/static/js/vendors.one.chunk.js:7628:19)
    at App

**Comment by djhi** [comment]
Please follow the issue template

**Comment by fzaninotto** [comment]
No news for some time, closing.
