### ISSUE TITLE
TabbedForm defaultValues: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by cduran-seeri** [marmelab/react-admin#7887]
**What you were expecting:**

`defaultValues` working as expected

**What happened instead:**

Maximum call stack size exceeded
![image](https://user-images.githubusercontent.com/92114179/175428550-738becb0-0aaa-4fd1-8529-a6778e50d5d5.png)

**Steps to reproduce:**

- Open simple example: https://codesandbox.io/s/red-dew-vlgtng?file=/src/comments/CommentCreate.tsx:463-508
- Navigate to Comments -> Create

**Related code:**

```jsx
const getDefaultValues = () => ({ body: "Test" })
const ExampleForm = () => (
  <TabbedForm defaultValues={getDefaultValues}>
    <FormTab label="Example">
      <TextInput source="body" />
    </FormTab>
  </TabbedForm>
)
```

**Other information:**

**Environment**

* React-admin version: 4.1.5
* Last version that did not exhibit the issue (if applicable):
* React version: 18.1.0
* Browser: Chrome 102
* Stack trace (in case of a JS error): 

```
Maximum call stack size exceeded

    at Form (https://vlgtng.sse.codesandbox.io/index.bundle.js:100736:26)
    at TabbedForm (https://vlgtng.sse.codesandbox.io/index.bundle.js:112945:93)
    at div
    at https://vlgtng.sse.codesandbox.io/index.bundle.js:589:66
    at Paper (https://vlgtng.sse.codesandbox.io/index.bundle.js:26636:82)
    at https://vlgtng.sse.codesandbox.io/index.bundle.js:589:66
    at Card (https://vlgtng.sse.codesandbox.io/index.bundle.js:11259:82)
    at div
    at div
    at https://vlgtng.sse.codesandbox.io/index.bundle.js:589:66
    at CreateView (https://vlgtng.sse.codesandbox.io/index.bundle.js:109387:25)
    at RecordContextProvider (https://vlgtng.sse.codesandbox.io/index.bundle.js:95999:23)
    at SaveContextProvider (https://vlgtng.sse.codesandbox.io/index.bundle.js:96093:23)
    at CreateContextProvider (https://vlgtng.sse.codesandbox.io/index.bundle.js:92489:23)
    at CreateBase (https://vlgtng.sse.codesandbox.io/index.bundle.js:92375:23)
    at Create (https://vlgtng.sse.codesandbox.io/index.bundle.js:109307:74)
    at CommentCreate
    at Routes (https://vlgtng.sse.codesandbox.io/index.bundle.js:158576:5)
    at ResourceContextProvider (https://vlgtng.sse.codesandbox.io/index.bundle.js:97217:23)
    at Resource (https://vlgtng.sse.codesandbox.io/index.bundle.js:97122:24)
    at Routes (https://vlgtng.sse.codesandbox.io/index.bundle.js:158576:5)
    at ErrorBoundary (https://vlgtng.sse.codesandbox.io/index.bundle.js:150858:37)
```

**Comment by fzaninotto** [comment]
Reproduced, thanks!
