### ISSUE TITLE
`helperText` on `Arrayinput` occurs `Cannot read properties of undefined (reading 'root')` error

### ISSUE THREAD

**Issue by Seojun-Park** [marmelab/react-admin#8273]
**What you were expecting:**
Showing `helperText` on `<ArrayInput />`

**What happened instead:**

Page is not loaded with `Cannot read properties of undefined (reading 'root')` error

**Steps to reproduce:**

Code sandbox : https://codesandbox.io/s/keen-benji-7hl4cu?file=/src/posts/PostCreate.tsx

1. Go to Post list
2. Click `Create` button

**Related code:**

https://codesandbox.io/s/keen-benji-7hl4cu?file=/src/posts/PostCreate.tsx:3528-3708

```
  <ArrayInput
          source="backlinks"
          defaultValue={backlinksDefaultValue}
          validate={[required()]}
          helperText="added helper text"
        >
```

**Other information:**

**Environment**

* React-admin version: "^4.4.0"
* Last version that did not exhibit the issue (if applicable):
* React version: "^17.0.2"
* Browser: Chrome
* Stack trace (in case of a JS error): 
```
Uncaught TypeError: Cannot read properties of undefined (reading 'root')
    at ArrayInput (ArrayInput.tsx:167:1)
    at renderWithHooks (react-dom.development.js:14985:1)
    at mountIndeterminateComponent (react-dom.development.js:17811:1)
    at beginWork (react-dom.development.js:19049:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3945:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994:1)
    at invokeGuardedCallback (react-dom.development.js:4056:1)
    at beginWork$1 (react-dom.development.js:23964:1)
    at performUnitOfWork (react-dom.development.js:22776:1)
    at workLoopSync (react-dom.development.js:22707:1)
```

**Comment by slax57** [comment]
Reproduced, thanks!
