### ISSUE TITLE
Cannot run the code with 'make'

### ISSUE THREAD

**Issue by Beslinda** [marmelab/react-admin#83]
I am learning React and I have tried to run your project several times but every time I fail . In my cmd I get the following msg:
log\node_modules\webpack-dev-server\bin\webpack-dev-server.js --port 8088 --proress --colors --hot --content-base., ...) failed.
make (e=2): The system cannot find the file specified.

I am using windows 8.1 , tell me in what other way I can run this code in reactjs.
Thank you

**Comment by adampatterson** [comment]
I tried building with Make and also got an error.

OSX 10.11.2

```
npm WARN EPEERINVALID react-medium-editor@1.6.1 requires a peer of react@^0.14.0 but none was installed.
npm WARN EPEERINVALID react-medium-editor@1.6.1 requires a peer of react-dom@^0.14.0 but none was installed.
npm WARN EPACKAGEJSON react-admin@0.0.1 No repository field.
npm WARN EBUNDLEOVERRIDE Replacing bundled bower > fs-write-stream-atomic with new installed version
Updating selenium standalone
downloading https://selenium-release.storage.googleapis.com/2.47/selenium-server-standalone-2.47.1.jar...
Updating chromedriver
downloading https://chromedriver.storage.googleapis.com/2.19/chromedriver_mac32.zip...
chromedriver_2.19.zip downloaded to /Users/adampatterson/Sites/react-admin-master/node_modules/protractor/selenium/chromedriver_2.19.zip
selenium-server-standalone-2.47.1.jar downloaded to /Users/adampatterson/Sites/react-admin-master/node_modules/protractor/selenium/selenium-server-standalone-2.47.1.jar
mkdir -p examples/blog/build/
mv node_modules/react-medium-editor node_modules/react-medium-editor_es6
./node_modules/babel/bin/babel/index.js node_modules/react-medium-editor_es6 --out-dir node_modules/react-medium-editor --stage 1 --compact false > /dev/null
/bin/sh: ./node_modules/babel/bin/babel/index.js: No such file or directory
make: *** [install] Error 127
```

**Comment by ilyabo** [comment]
Also failing to run the blog demo:

```
ilyabo blog$ make run
./node_modules/webpack-dev-server/bin/webpack-dev-server.js --port 8088 --progress --colors --hot --content-base .
module.js:341
    throw err;
    ^

Error: Cannot find module './router'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/Users/ilyabo/Workspace/_pantry/react-admin/examples/blog/node_modules/webpack-dev-server/node_modules/express/lib/application.js:17:14)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
make: *** [run] Error 1
ilyabo blog$ 

```

**Comment by fzaninotto** [comment]
This project is discontinued. We've published a complete rewrite and committed to support it. Check out [marmelab/admin-on-rest](https://github.com/marmelab/admin-on-rest).
