### ISSUE TITLE
Unit test fails immediately with "Show" component.

### ISSUE THREAD

**Issue by nikTSC** [marmelab/react-admin#8367]
**What you were expecting:**

I wanted to unit test my Functional Component, which uses the "Show" component from react admin, with react testing library.
It should be rendering everything to the DOM for me to find and check, that all the values are correct and all the elements are present.

**What happened instead:**

The test immediately fails with following error message: "TypeError: Cannot read properties of undefined (reading 'toLowerCase')".
I don't have a toLowerCase in my component, nor in any other component using the react admin library.

**Steps to reproduce:**

Test a custom component, using the "Show" component.

**Other information:**

Couldn't find anything, not even whether one can use React-Admin components in unit tests. ("Show" produces an error, "TextField" and "FunctionalField" work fine)
Maybe I was blind as well, but I was searching for nearly 2 hours.

**Environment**

* React-admin version: latest(4.5.0)
* Last version that did not exhibit the issue (if applicable): 
* React version: 18
* Browser: it's a test, but i use chrome/chromium for it
* Stack trace (in case of a JS error): 
Cannot read properties of undefined (reading 'toLowerCase')
TypeError: Cannot read properties of undefined (reading 'toLowerCase')
    at Object._apply_rules (/client/node_modules/inflection/lib/inflection.js:594:53)
    at Object.singularize (/client/node_modules/inflection/lib/inflection.js:692:24)
    at /client/node_modules/ra-core/src/core/useGetResourceLabel.ts:46:44
    at useShowController (/client/node_modules/ra-core/src/controller/show/useShowController.ts:91:15)
    at ShowBase (/client/node_modules/ra-core/src/controller/show/ShowBase.tsx:42:46)
    at renderWithHooks (/client/node_modules/react-dom/cjs/react-dom.development.js:14985:18)
    at mountIndeterminateComponent (/client/node_modules/react-dom/cjs/react-dom.development.js:17811:13)
    at beginWork (/client/node_modules/react-dom/cjs/react-dom.development.js:19049:16)
    at HTMLUnknownElement.callCallback (/client/node_modules/react-dom/cjs/react-dom.development.js:3945:14)
    at HTMLUnknownElement.callTheUserObjectsOperation (/client/node_modules/jsdom/lib/jsdom/living/generated/EventListener.js:26:30)
    at innerInvokeEventListeners (/client/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:350:25)
    at invokeEventListeners (/client/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:286:3)
    at HTMLUnknownElementImpl._dispatch (/client/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:233:9)
    at HTMLUnknownElementImpl.dispatchEvent (/client/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:104:17)
    at HTMLUnknownElement.dispatchEvent (/client/node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:241:34)
    at Object.invokeGuardedCallbackDev (/client/node_modules/react-dom/cjs/react-dom.development.js:3994:16)
    at invokeGuardedCallback (/client/node_modules/react-dom/cjs/react-dom.development.js:4056:31)
    at beginWork$1 (/client/node_modules/react-dom/cjs/react-dom.development.js:23964:7)
    at performUnitOfWork (/client/node_modules/react-dom/cjs/react-dom.development.js:22779:12)
    at workLoopSync (/client/node_modules/react-dom/cjs/react-dom.development.js:22707:5)
    at renderRootSync (/client/node_modules/react-dom/cjs/react-dom.development.js:22670:7)
    at performSyncWorkOnRoot (/client/node_modules/react-dom/cjs/react-dom.development.js:22293:18)
    at /client/node_modules/react-dom/cjs/react-dom.development.js:11327:26
    at unstable_runWithPriority (/client/node_modules/scheduler/cjs/scheduler.development.js:468:12)
    at runWithPriority$1 (/client/node_modules/react-dom/cjs/react-dom.development.js:11276:10)
    at flushSyncCallbackQueueImpl (/client/node_modules/react-dom/cjs/react-dom.development.js:11322:9)
    at flushSyncCallbackQueue (/client/node_modules/react-dom/cjs/react-dom.development.js:11309:3)
    at flushPassiveEffectsImpl (/client/node_modules/react-dom/cjs/react-dom.development.js:23620:3)
    at unstable_runWithPriority (/client/node_modules/scheduler/cjs/scheduler.development.js:468:12)
    at runWithPriority$1 (/client/node_modules/react-dom/cjs/react-dom.development.js:11276:10)
    at flushPassiveEffects (/client/node_modules/react-dom/cjs/react-dom.development.js:23447:14)
    at Object.<anonymous>.flushWork (/client/node_modules/react-dom/cjs/react-dom-test-utils.development.js:992:10)
    at act (/client/node_modules/react-dom/cjs/react-dom-test-utils.development.js:1107:9)
    at render (/client/node_modules/@testing-library/react/dist/pure.js:97:26)
    at /client/src/containers/KeyShow/KeyShow.unit.test.tsx:20:11
    at step (/client/src/containers/KeyShow/KeyShow.unit.test.tsx:44:23)
    at Object.next (/client/src/containers/KeyShow/KeyShow.unit.test.tsx:25:53)
    at /client/src/containers/KeyShow/KeyShow.unit.test.tsx:19:71
    at new Promise (<anonymous>)
    at Object.<anonymous>.__awaiter (/client/src/containers/KeyShow/KeyShow.unit.test.tsx:15:12)
    at Object.<anonymous> (/client/src/containers/KeyShow/KeyShow.unit.test.tsx:19:40)
    at Promise.then.completed (/client/node_modules/jest-circus/build/utils.js:289:28)
    at new Promise (<anonymous>)
    at callAsyncCircusFn (/client/node_modules/jest-circus/build/utils.js:222:10)
    at _callCircusTest (/client/node_modules/jest-circus/build/run.js:248:40)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at _runTest (/client/node_modules/jest-circus/build/run.js:184:3)
    at _runTestsForDescribeBlock (/client/node_modules/jest-circus/build/run.js:86:9)
    at _runTestsForDescribeBlock (/client/node_modules/jest-circus/build/run.js:81:9)
    at run (/client/node_modules/jest-circus/build/run.js:26:3)
    at runAndTransformResultsToJestFormat (/client/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapterInit.js:120:21)
    at jestAdapter (client/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:79:19)
    at runTestInternal (/client/node_modules/jest-runner/build/runTest.js:367:16)
    at runTest (/client/node_modules/jest-runner/build/runTest.js:444:34)

**Comment by fzaninotto** [comment]
We have numerous integration tests for the Show component working fine in the codebase (see e.g. https://github.com/marmelab/react-admin/blob/master/packages/ra-ui-materialui/src/detail/Show.spec.tsx). 

There must be something wrong with your setup. Please For the simple example codesandbox and modify it to reproduce the issue. 

https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple

**Comment by nikTSC** [comment]
There was indeed something wrong with my setup. I didn't await the screen query....
Works fine now, thanks for the first link.
