### ISSUE TITLE
useController Cannot read properties of null (reading 'control')

### ISSUE THREAD

**Issue by crtl** [marmelab/react-admin#8464]
**What you were expecting:**
Hook should work.

**What happened instead:**
Error is thrown because `useFormContext` inside `useController` returns null.
```
useController.ts:52 Uncaught TypeError: Cannot read properties of null (reading 'control')
    at useController (useController.ts:52:35)
```

**Steps to reproduce:**
I am following the documentation on how to create a custom input and have created the following component:
```ts
// SynonymsInput.tsx
import {FC} from "react";
import {useController} from "react-hook-form";

export const SynonymsInput: FC = (props) => {
    const controller = useController({name: "synonyms", defaultValue: ""}); // error is thrown here

    return <input {...controller.field} />
};
SynonymsInput.displayName = "SynonymsInput";

// CommunityEdit.tsx
import {FC} from "react";
import {Edit, SimpleForm} from "react-admin";
import {SynonymsInput} from "@admin/app/communities/input/SynonymsInput";

export const CommunityEdit: FC = (props) => {
    return <Edit>
        <SimpleForm>
            <SynonymsInput />
        </SimpleForm>
    </Edit>
}:
```

**Other information:**

**Environment**

* React-admin version: 4.6.0
* React version: 17.0.2
* Browser: chrome
* Stack trace (in case of a JS error):
```
useController.ts:52 Uncaught TypeError: Cannot read properties of null (reading 'control')
    at useController (useController.ts:52:35)
    at SynonymsInput (SynonymsInput.tsx:6:24)
    at renderWithHooks (react-dom.development.js:14985:18)
    at mountIndeterminateComponent (react-dom.development.js:17811:13)
    at beginWork (react-dom.development.js:19049:16)
    at HTMLUnknownElement.callCallback2 (react-dom.development.js:3945:14)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994:16)
    at invokeGuardedCallback (react-dom.development.js:4056:31)
    at beginWork$1 (react-dom.development.js:23964:7)
    at performUnitOfWork (react-dom.development.js:22776:12)
useController @ useController.ts:52
SynonymsInput @ SynonymsInput.tsx:6
renderWithHooks @ react-dom.development.js:14985
mountIndeterminateComponent @ react-dom.development.js:17811
beginWork @ react-dom.development.js:19049
callCallback2 @ react-dom.development.js:3945
invokeGuardedCallbackDev @ react-dom.development.js:3994
invokeGuardedCallback @ react-dom.development.js:4056
beginWork$1 @ react-dom.development.js:23964
performUnitOfWork @ react-dom.development.js:22776
workLoopSync @ react-dom.development.js:22707
renderRootSync @ react-dom.development.js:22670
performSyncWorkOnRoot @ react-dom.development.js:22293
(anonymous) @ react-dom.development.js:11327
unstable_runWithPriority @ scheduler.development.js:468
runWithPriority$1 @ react-dom.development.js:11276
flushSyncCallbackQueueImpl @ react-dom.development.js:11322
flushSyncCallbackQueue @ react-dom.development.js:11309
batchedUpdates$1 @ react-dom.development.js:22387
(anonymous) @ notifyManager.js:75
Promise.then (async)
scheduleMicrotask @ utils.js:322
flush @ notifyManager.js:74
batch @ notifyManager.js:30
dispatch @ query.js:392
setData @ query.js:85
onSuccess @ query.js:336
resolve2 @ retryer.js:58
Promise.then (async)
run2 @ retryer.js:116
Retryer2 @ retryer.js:156
fetch @ query.js:332
executeFetch @ queryObserver.js:199
onSubscribe @ queryObserver.js:40
subscribe @ subscribable.js:16
(anonymous) @ useBaseQuery.js:60
invokePassiveEffectCreate @ react-dom.development.js:23487
callCallback2 @ react-dom.development.js:3945
invokeGuardedCallbackDev @ react-dom.development.js:3994
invokeGuardedCallback @ react-dom.development.js:4056
flushPassiveEffectsImpl @ react-dom.development.js:23574
unstable_runWithPriority @ scheduler.development.js:468
runWithPriority$1 @ react-dom.development.js:11276
flushPassiveEffects @ react-dom.development.js:23447
performSyncWorkOnRoot @ react-dom.development.js:22269
(anonymous) @ react-dom.development.js:11327
unstable_runWithPriority @ scheduler.development.js:468
runWithPriority$1 @ react-dom.development.js:11276
flushSyncCallbackQueueImpl @ react-dom.development.js:11322
flushSyncCallbackQueue @ react-dom.development.js:11309
scheduleUpdateOnFiber @ react-dom.development.js:21893
dispatchAction @ react-dom.development.js:16139
(anonymous) @ CoreAdminRoutes.tsx:47
Promise.then (async)
(anonymous) @ CoreAdminRoutes.tsx:46
invokePassiveEffectCreate @ react-dom.development.js:23487
callCallback2 @ react-dom.development.js:3945
invokeGuardedCallbackDev @ react-dom.development.js:3994
invokeGuardedCallback @ react-dom.development.js:4056
flushPassiveEffectsImpl @ react-dom.development.js:23574
unstable_runWithPriority @ scheduler.development.js:468
runWithPriority$1 @ react-dom.development.js:11276
flushPassiveEffects @ react-dom.development.js:23447
(anonymous) @ react-dom.development.js:23324
workLoop @ scheduler.development.js:417
flushWork @ scheduler.development.js:390
performWorkUntilDeadline @ scheduler.development.js:157
react_devtools_backend.js:4012 The above error occurred in the <SynonymsInput> component:

    at SynonymsInput (http://localhost:3000/src/admin/app/communities/input/SynonymsInput.tsx?t=1670080924211:20:22)
    at div
    at http://localhost:3000/node_modules/.vite/deps/chunk-VLSYDROJ.js?v=ec19e293:1374:50
    at Stack3 (http://localhost:3000/node_modules/.vite/deps/react-admin.js?v=b146aea4:53933:22)
    at div
    at http://localhost:3000/node_modules/.vite/deps/chunk-VLSYDROJ.js?v=ec19e293:1374:50
    at CardContent2 (http://localhost:3000/node_modules/.vite/deps/react-admin.js?v=b146aea4:40130:17)
    at DefaultComponent3 (http://localhost:3000/node_modules/.vite/deps/react-admin.js?v=b146aea4:71557:22)
    at form
    at FormGroupsProvider (http://localhost:3000/node_modules/.vite/deps/react-admin.js?v=b146aea4:31597:22)
    at FormProvider (http://localhost:3000/node_modules/.vite/deps/react-admin.js?v=b146aea4:25667:11)
    at LabelPrefixContextProvider (http://localhost:3000/node_modules/.vite/deps/react-admin.js?v=b146aea4:30501:20)
    at RecordContextProvider (http://localhost:3000/node_modules/.vite/deps/react-admin.js?v=b146aea4:23784:22)
    at OptionalRecordContextProvider (http://localhost:3000/node_modules/.vite/deps/react-admin.js?v=b146aea4:24154:19)
    at Form2 (http://localhost:3000/node_modules/.vite/deps/react-admin.js?v=b146aea4:31991:24)
    at SimpleForm (http://localhost:3000/node_modules/.vite/deps/react-admin.js?v=b146aea4:71537:24)
    at div
    at http://localhost:3000/node_modules/.vite/deps/chunk-VLSYDROJ.js?v=ec19e293:1374:50
    at Paper2 (http://localhost:3000/node_modules/.vite/deps/react-admin.js?v=b146aea4:33315:17)
    at http://localhost:3000/node_modules/.vite/deps/chunk-VLSYDROJ.js?v=ec19e293:1374:50
    at Card2 (http://localhost:3000/node_modules/.vite/deps/react-admin.js?v=b146aea4:39870:17)
    at div
    at div
    at http://localhost:3000/node_modules/.vite/deps/chunk-VLSYDROJ.js?v=ec19e293:1374:50
    at EditView (http://localhost:3000/node_modules/.vite/deps/react-admin.js?v=b146aea4:70924:23)
    at RecordContextProvider (http://localhost:3000/node_modules/.vite/deps/react-admin.js?v=b146aea4:23784:22)
    at SaveContextProvider (http://localhost:3000/node_modules/.vite/deps/react-admin.js?v=b146aea4:23437:22)
    at EditContextProvider (http://localhost:3000/node_modules/.vite/deps/react-admin.js?v=b146aea4:24178:22)
    at EditBase (http://localhost:3000/node_modules/.vite/deps/react-admin.js?v=b146aea4:24204:22)
    at Edit (http://localhost:3000/node_modules/.vite/deps/react-admin.js?v=b146aea4:71015:3)
    at CommunityEdit
    at RenderedRoute (http://localhost:3000/node_modules/.vite/deps/react-admin.js?v=b146aea4:20106:5)
    at Routes (http://localhost:3000/node_modules/.vite/deps/react-admin.js?v=b146aea4:20306:5)
    at ResourceContextProvider (http://localhost:3000/node_modules/.vite/deps/react-admin.js?v=b146aea4:29994:22)
    at Resource (http://localhost:3000/node_modules/.vite/deps/react-admin.js?v=b146aea4:30000:23)
    at RenderedRoute (http://localhost:3000/node_modules/.vite/deps/react-admin.js?v=b146aea4:20106:5)
    at Routes (http://localhost:3000/node_modules/.vite/deps/react-admin.js?v=b146aea4:20306:5)
    at ErrorBoundary2 (http://localhost:3000/node_modules/.vite/deps/react-admin.js?v=b146aea4:62078:35)
    at div
    at main
    at div
    at div
    at http://localhost:3000/node_modules/.vite/deps/chunk-VLSYDROJ.js?v=ec19e293:1374:50
    at Layout (http://localhost:3000/node_modules/.vite/deps/react-admin.js?v=b146aea4:62393:19)
    at div
    at RenderedRoute (http://localhost:3000/node_modules/.vite/deps/react-admin.js?v=b146aea4:20106:5)
    at Routes (http://localhost:3000/node_modules/.vite/deps/react-admin.js?v=b146aea4:20306:5)
    at CoreAdminRoutes (http://localhost:3000/node_modules/.vite/deps/react-admin.js?v=b146aea4:29879:28)
    at RenderedRoute (http://localhost:3000/node_modules/.vite/deps/react-admin.js?v=b146aea4:20106:5)
    at Routes (http://localhost:3000/node_modules/.vite/deps/react-admin.js?v=b146aea4:20306:5)
    at CoreAdminUI (http://localhost:3000/node_modules/.vite/deps/react-admin.js?v=b146aea4:29943:19)
    at div
    at http://localhost:3000/node_modules/.vite/deps/chunk-VLSYDROJ.js?v=ec19e293:1374:50
    at ScopedCssBaseline2 (http://localhost:3000/node_modules/.vite/deps/react-admin.js?v=b146aea4:50544:17)
    at AdminUI (http://localhost:3000/node_modules/.vite/deps/react-admin.js?v=b146aea4:74896:26)
    at InnerThemeProvider (http://localhost:3000/node_modules/.vite/deps/react-admin.js?v=b146aea4:3407:17)
    at ThemeProvider (http://localhost:3000/node_modules/.vite/deps/react-admin.js?v=b146aea4:2816:5)
    at ThemeProvider2 (http://localhost:3000/node_modules/.vite/deps/react-admin.js?v=b146aea4:3415:5)
    at ThemeProvider3 (http://localhost:3000/node_modules/.vite/deps/react-admin.js?v=b146aea4:62879:22)
    at ResourceDefinitionContextProvider (http://localhost:3000/node_modules/.vite/deps/react-admin.js?v=b146aea4:29507:16)
    at NotificationContextProvider (http://localhost:3000/node_modules/.vite/deps/react-admin.js?v=b146aea4:21214:22)
    at I18nContextProvider (http://localhost:3000/node_modules/.vite/deps/react-admin.js?v=b146aea4:21290:16)
    at Router (http://localhost:3000/node_modules/.vite/deps/react-admin.js?v=b146aea4:20253:15)
    at HistoryRouter2 (http://localhost:3000/node_modules/.vite/deps/react-admin.js?v=b146aea4:21708:22)
    at InternalRouter (http://localhost:3000/node_modules/.vite/deps/react-admin.js?v=b146aea4:21748:22)
    at BasenameContextProvider (http://localhost:3000/node_modules/.vite/deps/react-admin.js?v=b146aea4:21728:22)
    at AdminRouter (http://localhost:3000/node_modules/.vite/deps/react-admin.js?v=b146aea4:21734:21)
    at QueryClientProvider2 (http://localhost:3000/node_modules/.vite/deps/chunk-NDHQLVV3.js?v=ec19e293:2669:21)
    at PreferencesEditorContextProvider (http://localhost:3000/node_modules/.vite/deps/react-admin.js?v=b146aea4:29423:22)
    at StoreContextProvider (http://localhost:3000/node_modules/.vite/deps/react-admin.js?v=b146aea4:21104:19)
    at CoreAdminContext (http://localhost:3000/node_modules/.vite/deps/react-admin.js?v=b146aea4:29532:28)
    at AdminContext (http://localhost:3000/node_modules/.vite/deps/react-admin.js?v=b146aea4:74939:19)
    at Admin (http://localhost:3000/node_modules/.vite/deps/react-admin.js?v=b146aea4:75209:28)
    at ConfirmDialogProvider (http://localhost:3000/src/admin/app/shared/ConfirmDialogContext.tsx:24:31)
    at Fe (http://localhost:3000/node_modules/.vite/deps/styled-components.js?v=0b3d383f:1112:40)
    at Home

```

**Comment by fzaninotto** [comment]
This works fine in our apps and tests, it must be linked to something specific on your side. Could you check your package lock file for a duplicate entry for react-hook-form? If not, please build a reproduction based on the simple example codesandbox.

**Comment by crtl** [comment]
Thanks, ive resolved it by removing react-hook-form from my package.json
