### ISSUE TITLE
ra-input-rich-text: The Mention extension doesn't work correctly after saving the field.

### ISSUE THREAD

**Issue by olesmarola** [marmelab/react-admin#8571]
**What you were expecting:**
Mention extension works correctly with existing text and mentions, and first mention edit list close after Enter key press. When trying to select an item using the mouse, everything is ok, but when using a keyboard, got an issue with the list.

**What happened instead:**
When trying to edit the first mention after pressing enter key list with mentions doesn't close. Here is a video of this issue [https://share.cleanshot.com/dNJpQ9xf](https://share.cleanshot.com/dNJpQ9xf) and here is an example with search: [https://share.cleanshot.com/SgJd0PjZ](https://share.cleanshot.com/SgJd0PjZ)
Got the error: flushSync was called from inside a lifecycle method. React cannot flush when React is already rendering. Consider moving this call to a scheduler task or microtask.

**Steps to reproduce:**
1. Add mention extension.
2. Configure rich text input with options that contain extension.
3. Use it a few times in one input.
4. Save.
5. Edit the first mention.
6. Got errors and unexpected behavior.

**Related code:**
I used code sample from the official docs example: [https://tiptap.dev/api/nodes/mention#usage](https://tiptap.dev/api/nodes/mention#usage)  and react admin docs: [https://marmelab.com/react-admin/RichTextInput.html](https://marmelab.com/react-admin/RichTextInput.html)

```
const RichTextInput: FC<InputProps> = (props) => {
const { data: questions } = useGetList('step');

  const editorOptions = useMemo(
    () => ({
      ...DefaultEditorOptions,
      extensions: [
        ...DefaultEditorOptions.extensions,
        Mention.configure({
          HTMLAttributes: {
            class: 'question',
          },
          suggestion: {
            allowSpaces: true,
            items: ({ query }) => {
            if (!questions) return [];
                  return questions.map((question) => {
                  const questionId = question.fields.find((field: SimpleField) => field.title === 'Question id')?.value;
                  const questionTitle = question.title;

                  return {
                    id: questionId,
                    title: questionTitle,
                  };
                })
                .filter((question) => question.title.toLowerCase().startsWith(query.toLowerCase()))
                .slice(0, 5);
            },
            render: () => {
              let component: any;
              let popup: any;

              return {
                onStart: (props) => {
                  component = new ReactRenderer(QuestionsList, {
                    props,
                    editor: props.editor,
                  });

                  if (!props.clientRect) {
                    return;
                  }

              
                  popup = tippy('body', {
                    getReferenceClientRect: props.clientRect,
                    appendTo: () => document.body,
                    content: component.element,
                    showOnCreate: true,
                    interactive: true,
                    trigger: 'manual',
                    placement: 'bottom-start',
                  });
                },

                onUpdate(props) {
                  component.updateProps(props);

                  if (!props.clientRect) {
                    return;
                  }

                  popup[0].setProps({
                    getReferenceClientRect: props.clientRect,
                  });
                },

                onKeyDown(props) {
                  if (props.event.key === 'Escape') {
                    popup[0].hide();

                    return true;
                  }

                  return component.ref?.onKeyDown(props);
                },

                onExit() {
                  popup?.[0]?.destroy();
                  component?.destroy();
                },
              };
            },
          },
        }),
      ],
    }),
    [questions],
  );
  if (!questions) return null;

  return <RaRichTextInput toolbar={<Toolbar />} editorOptions={editorOptions} {...props} />;
```

**Other information:**

**Environment**

* React-admin version: 4.6.1 
* Last version that did not exhibit the issue (if applicable): -
* React version: 18.2.0
* Browser: Chrome 108.0.5359.124 (Official Build) (arm64)
* Stack trace (in case of a JS error):
```
Warning: flushSync was called from inside a lifecycle method. React cannot flush when React is already rendering. Consider moving this call to a scheduler task or micro task.
    at RichTextInput (webpack-internal:///./node_modules/ra-input-rich-text/dist/esm/RichTextInput.js:104:27)
    at RichTextInput (webpack-internal:///./src/admin/components/generic/form/custom-inputs/rich-text-input/rich-text-input.tsx:27:89)
    at EditFormFields (webpack-internal:///./src/admin/components/generic/form/edit-form/edit-form-fields/edit-form-fields.tsx:28:11)
    at div
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-6a883da9.browser.esm.js:57:66)
    at Stack (webpack-internal:///./node_modules/@mui/material/Stack/Stack.js:118:87)
    at FormGroupContextProvider (webpack-internal:///./node_modules/ra-core/dist/esm/form/FormGroupContextProvider.js:58:23)
    at FormTab (webpack-internal:///./node_modules/ra-ui-materialui/dist/esm/form/FormTab.js:40:27)
    at div
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-6a883da9.browser.esm.js:57:66)
    at CardContent (webpack-internal:///./node_modules/@mui/material/CardContent/CardContent.js:48:82)
    at DefaultComponent (webpack-internal:///./node_modules/ra-ui-materialui/dist/esm/form/TabbedFormView.js:105:23)
    at div
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-6a883da9.browser.esm.js:57:66)
    at TabbedFormView (webpack-internal:///./node_modules/ra-ui-materialui/dist/esm/form/TabbedFormView.js:50:26)
    at form
    at FormGroupsProvider (webpack-internal:///./node_modules/ra-core/dist/esm/form/FormGroupsProvider.js:28:23)
    at FormProvider (webpack-internal:///./node_modules/react-hook-form/dist/index.esm.mjs:141:13)
    at LabelPrefixContextProvider (webpack-internal:///./node_modules/ra-core/dist/esm/util/LabelPrefixContextProvider.js:13:21)
    at RecordContextProvider (webpack-internal:///./node_modules/ra-core/dist/esm/controller/record/RecordContext.js:41:23)
    at OptionalRecordContextProvider (webpack-internal:///./node_modules/ra-core/dist/esm/controller/record/OptionalRecordContextProvider.js:26:20)
    at Form (webpack-internal:///./node_modules/ra-core/dist/esm/form/Form.js:59:26)
    at TabbedForm (webpack-internal:///./node_modules/ra-ui-materialui/dist/esm/form/TabbedForm.js:116:93)
    at Form (webpack-internal:///./src/admin/components/resources/steps/steps-edit.tsx:22:91)
    at div
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-6a883da9.browser.esm.js:57:66)
    at Paper (webpack-internal:///./node_modules/@mui/material/Paper/Paper.js:77:83)
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-6a883da9.browser.esm.js:57:66)
    at Card (webpack-internal:///./node_modules/@mui/material/Card/Card.js:49:82)
    at div
    at div
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-6a883da9.browser.esm.js:57:66)
    at EditView (webpack-internal:///./node_modules/ra-ui-materialui/dist/esm/detail/EditView.js:49:25)
    at RecordContextProvider (webpack-internal:///./node_modules/ra-core/dist/esm/controller/record/RecordContext.js:41:23)
    at SaveContextProvider (webpack-internal:///./node_modules/ra-core/dist/esm/controller/saveContext/SaveContextProvider.js:11:23)
    at EditContextProvider (webpack-internal:///./node_modules/ra-core/dist/esm/controller/edit/EditContextProvider.js:38:23)
    at EditBase (webpack-internal:///./node_modules/ra-core/dist/esm/controller/edit/EditBase.js:55:23)
    at Edit (webpack-internal:///./node_modules/ra-ui-materialui/dist/esm/detail/Edit.js:84:74)
    at StepsEdit
    at RenderedRoute (webpack-internal:///./node_modules/react-router/dist/index.js:714:5)
    at Routes (webpack-internal:///./node_modules/react-router/dist/index.js:1162:5)
    at ResourceContextProvider (webpack-internal:///./node_modules/ra-core/dist/esm/core/ResourceContextProvider.js:30:23)
    at Resource (webpack-internal:///./node_modules/ra-core/dist/esm/core/Resource.js:14:24)
    at RenderedRoute (webpack-internal:///./node_modules/react-router/dist/index.js:714:5)
    at Routes (webpack-internal:///./node_modules/react-router/dist/index.js:1162:5)
    at ErrorBoundary (webpack-internal:///./node_modules/react-error-boundary/dist/react-error-boundary.umd.js:69:37)
    at div
    at main
    at div
    at div
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-6a883da9.browser.esm.js:57:66)
    at Layout (webpack-internal:///./node_modules/ra-ui-materialui/dist/esm/layout/Layout.js:53:20)
    at CustomLayout
    at div
    at RenderedRoute (webpack-internal:///./node_modules/react-router/dist/index.js:714:5)
    at Routes (webpack-internal:///./node_modules/react-router/dist/index.js:1162:5)
    at CoreAdminRoutes (webpack-internal:///./node_modules/ra-core/dist/esm/core/CoreAdminRoutes.js:20:79)
    at RenderedRoute (webpack-internal:///./node_modules/react-router/dist/index.js:714:5)
    at Routes (webpack-internal:///./node_modules/react-router/dist/index.js:1162:5)
    at CoreAdminUI (webpack-internal:///./node_modules/ra-core/dist/esm/core/CoreAdminUI.js:20:20)
    at div
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-6a883da9.browser.esm.js:57:66)
    at ScopedCssBaseline (webpack-internal:///./node_modules/@mui/material/ScopedCssBaseline/ScopedCssBaseline.js:64:82)
    at AdminUI (webpack-internal:///./node_modules/ra-ui-materialui/dist/esm/AdminUI.js:40:27)
    at InnerThemeProvider (webpack-internal:///./node_modules/@mui/system/esm/ThemeProvider/ThemeProvider.js:21:70)
    at ThemeProvider (webpack-internal:///./node_modules/@mui/private-theming/ThemeProvider/ThemeProvider.js:43:5)
    at ThemeProvider (webpack-internal:///./node_modules/@mui/system/esm/ThemeProvider/ThemeProvider.js:40:5)
    at ThemeProvider (webpack-internal:///./node_modules/ra-ui-materialui/dist/esm/layout/Theme/ThemeProvider.js:21:23)
    at ResourceDefinitionContextProvider (webpack-internal:///./node_modules/ra-core/dist/esm/core/ResourceDefinitionContext.js:61:17)
    at NotificationContextProvider (webpack-internal:///./node_modules/ra-core/dist/esm/notification/NotificationContextProvider.js:23:23)
    at I18nContextProvider (webpack-internal:///./node_modules/ra-core/dist/esm/i18n/I18nContextProvider.js:19:17)
    at Router (webpack-internal:///./node_modules/react-router/dist/index.js:1094:15)
    at HistoryRouter (webpack-internal:///./node_modules/ra-core/dist/esm/routing/HistoryRouter.js:16:23)
    at InternalRouter (webpack-internal:///./node_modules/ra-core/dist/esm/routing/AdminRouter.js:33:23)
    at BasenameContextProvider (webpack-internal:///./node_modules/ra-core/dist/esm/routing/BasenameContextProvider.js:19:23)
    at AdminRouter (webpack-internal:///./node_modules/ra-core/dist/esm/routing/AdminRouter.js:22:22)
    at QueryClientProvider (webpack-internal:///./node_modules/react-query/es/react/QueryClientProvider.js:39:21)
    at PreferencesEditorContextProvider (webpack-internal:///./node_modules/ra-core/dist/esm/preferences/PreferencesEditorContextProvider.js:12:23)
    at StoreContextProvider (webpack-internal:///./node_modules/ra-core/dist/esm/store/StoreContextProvider.js:12:20)
    at CoreAdminContext (webpack-internal:///./node_modules/ra-core/dist/esm/core/CoreAdminContext.js:28:30)
    at AdminContext (webpack-internal:///./node_modules/ra-ui-materialui/dist/esm/AdminContext.js:37:20)
    at Admin (webpack-internal:///./node_modules/react-admin/dist/esm/Admin.js:98:30)
    at App
    at LoadableImpl (webpack-internal:///./node_modules/next/dist/shared/lib/loadable.js:90:9)
    at Home
    at PathnameContextProviderAdapter (webpack-internal:///./node_modules/next/dist/shared/lib/router/adapters.js:62:11)
    at ErrorBoundary (webpack-internal:///./node_modules/next/dist/compiled/@next/react-dev-overlay/dist/client.js:301:63)
    at ReactDevOverlay (webpack-internal:///./node_modules/next/dist/compiled/@next/react-dev-overlay/dist/client.js:850:919)
    at Container (webpack-internal:///./node_modules/next/dist/client/index.js:60:1)
    at AppContainer (webpack-internal:///./node_modules/next/dist/client/index.js:173:11)
    at Root (webpack-internal:///./node_modules/next/dist/client/index.js:346:11)
```

**Comment by olesmarola** [comment]
I also noticed that onStart function triggers twice, and first onExit triggers before the component and popup have been created. And after that, trigger a second onStart that rewrites variables (component and popup) where was first component instance and popup that was not destroyed, so onExit, we destroy only the last elements. And we have an uncontrolled first popup: [https://share.cleanshot.com/r6YLGL78](https://share.cleanshot.com/r6YLGL78)

**Comment by slax57** [comment]
The way I see it, this issue has high chances of finding its root in the tiptap code or in your implementation.
Unless you can prove it actually comes from a bug in react-admin, by for example comparing the same implementation with and without react-admin - and most importantly provide a codesandbox or a stackblitz for us to work with - we probably won't work on this issue.

**Comment by fzaninotto** [comment]
No news for some time, closing.
