### ISSUE TITLE
[BUG] Failed prop type: Invalid prop `filter` of type `array` supplied to `List`, expected `object`.

### ISSUE THREAD

**Issue by TangMonk** [marmelab/react-admin#8806]
```
const postFilters = [
    <TextInput label="Search" source="q" alwaysOn />,
    <TextInput label="Title" source="title" defaultValue="Hello, World!" />,
];

export const PostList = () => (
    <List filters={postFilters}>
        ...
    </List>
);
```

**Environment**

* React-admin version: react-admin@4.9.1
* Last version that did not exhibit the issue (if applicable):
* React version: react@18.2.0
* Browser: Chrome
* Stack trace (in case of a JS error):
```
react-jsx-dev-runtime.development.js:87 Warning: Failed prop type: Invalid prop `filter` of type `array` supplied to `List`, expected `object`.
    at List (http://localhost:5176/node_modules/.vite/deps/react-admin.js?v=5b635593:22151:23)
    at PaidUserTxList (http://localhost:5176/src/Resources/PaidUserTx.jsx?t=1680688101395:38:19)
    at RenderedRoute (http://localhost:5176/node_modules/.vite/deps/chunk-BQTNGUNJ.js?v=5b635593:9935:5)
    at Routes (http://localhost:5176/node_modules/.vite/deps/chunk-BQTNGUNJ.js?v=5b635593:10172:5)
    at ResourceContextProvider (http://localhost:5176/node_modules/.vite/deps/chunk-BQTNGUNJ.js?v=5b635593:21274:21)
    at Resource (http://localhost:5176/node_modules/.vite/deps/chunk-BQTNGUNJ.js?v=5b635593:21280:22)
    at RenderedRoute (http://localhost:5176/node_modules/.vite/deps/chunk-BQTNGUNJ.js?v=5b635593:9935:5)
    at Routes (http://localhost:5176/node_modules/.vite/deps/chunk-BQTNGUNJ.js?v=5b635593:10172:5)
    at ErrorBoundary2 (http://localhost:5176/node_modules/.vite/deps/react-admin.js?v=5b635593:6640:35)
    at div
    at main
    at div
    at div
    at http://localhost:5176/node_modules/.vite/deps/chunk-22TKTHL3.js?v=5b635593:3817:51
    at Layout (http://localhost:5176/node_modules/.vite/deps/react-admin.js?v=5b635593:6961:19)
    at div
    at RenderedRoute (http://localhost:5176/node_modules/.vite/deps/chunk-BQTNGUNJ.js?v=5b635593:9935:5)
    at Routes (http://localhost:5176/node_modules/.vite/deps/chunk-BQTNGUNJ.js?v=5b635593:10172:5)
    at CoreAdminRoutes (http://localhost:5176/node_modules/.vite/deps/chunk-BQTNGUNJ.js?v=5b635593:21158:28)
    at RenderedRoute (http://localhost:5176/node_modules/.vite/deps/chunk-BQTNGUNJ.js?v=5b635593:9935:5)
    at Routes (http://localhost:5176/node_modules/.vite/deps/chunk-BQTNGUNJ.js?v=5b635593:10172:5)
    at CoreAdminUI (http://localhost:5176/node_modules/.vite/deps/chunk-BQTNGUNJ.js?v=5b635593:21222:18)
    at div
    at http://localhost:5176/node_modules/.vite/deps/chunk-22TKTHL3.js?v=5b635593:3817:51
    at ScopedCssBaseline2 (http://localhost:5176/node_modules/.vite/deps/chunk-22TKTHL3.js?v=5b635593:46829:17)
    at AdminUI (http://localhost:5176/node_modules/.vite/deps/react-admin.js?v=5b635593:22733:26)
    at InnerThemeProvider (http://localhost:5176/node_modules/.vite/deps/chunk-22TKTHL3.js?v=5b635593:6944:17)
    at ThemeProvider2 (http://localhost:5176/node_modules/.vite/deps/chunk-22TKTHL3.js?v=5b635593:6266:15)
    at ThemeProvider3 (http://localhost:5176/node_modules/.vite/deps/chunk-22TKTHL3.js?v=5b635593:6952:15)
    at ThemeProvider (http://localhost:5176/node_modules/.vite/deps/react-admin.js?v=5b635593:7448:22)
    at ResourceDefinitionContextProvider (http://localhost:5176/node_modules/.vite/deps/chunk-BQTNGUNJ.js?v=5b635593:20781:15)
    at NotificationContextProvider (http://localhost:5176/node_modules/.vite/deps/chunk-BQTNGUNJ.js?v=5b635593:6176:21)
    at I18nContextProvider (http://localhost:5176/node_modules/.vite/deps/chunk-BQTNGUNJ.js?v=5b635593:21798:15)
    at Router (http://localhost:5176/node_modules/.vite/deps/chunk-BQTNGUNJ.js?v=5b635593:10119:15)
    at HistoryRouter2 (http://localhost:5176/node_modules/.vite/deps/chunk-BQTNGUNJ.js?v=5b635593:11012:21)
    at InternalRouter (http://localhost:5176/node_modules/.vite/deps/chunk-BQTNGUNJ.js?v=5b635593:11052:21)
    at BasenameContextProvider (http://localhost:5176/node_modules/.vite/deps/chunk-BQTNGUNJ.js?v=5b635593:11032:21)
    at AdminRouter (http://localhost:5176/node_modules/.vite/deps/chunk-BQTNGUNJ.js?v=5b635593:11038:20)
    at QueryClientProvider2 (http://localhost:5176/node_modules/.vite/deps/chunk-BQTNGUNJ.js?v=5b635593:8932:21)
    at PreferencesEditorContextProvider (http://localhost:5176/node_modules/.vite/deps/chunk-BQTNGUNJ.js?v=5b635593:20697:21)
    at StoreContextProvider (http://localhost:5176/node_modules/.vite/deps/chunk-BQTNGUNJ.js?v=5b635593:6084:18)
    at CoreAdminContext (http://localhost:5176/node_modules/.vite/deps/chunk-BQTNGUNJ.js?v=5b635593:20807:28)
    at AdminContext (http://localhost:5176/node_modules/.vite/deps/react-admin.js?v=5b635593:22777:19)
    at Admin (http://localhost:5176/node_modules/.vite/deps/react-admin.js?v=5b635593:23048:28)
    at App
printWarning @ react-jsx-dev-runtime.development.js:87
error @ react-jsx-dev-runtime.development.js:61
checkPropTypes @ react-jsx-dev-runtime.development.js:631
validatePropTypes @ react-jsx-dev-runtime.development.js:1164
jsxWithValidation @ react-jsx-dev-runtime.development.js:1284
PaidUserTxList @ PaidUserTx.jsx:46
renderWithHooks @ react-dom.development.js:16305
mountIndeterminateComponent @ react-dom.development.js:20074
beginWork @ react-dom.development.js:21587
beginWork$1 @ react-dom.development.js:27426
performUnitOfWork @ react-dom.development.js:26557
workLoopSync @ react-dom.development.js:26466
renderRootSync @ react-dom.development.js:26434
performConcurrentWorkOnRoot @ react-dom.development.js:25738
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
useDataProvider.ts:133 TypeError: Cannot convert a Symbol value to a string
    at encodeURIComponent (<anonymous>)
    at module.exports (index.js:2:25)
    at encode (index.js:225:27)
    at index.js:419:39
    at Array.map (<anonymous>)
    at exports.stringify (index.js:398:14)
    at Object.getList (index.ts:47:46)
    at Proxy.<anonymous> (useDataProvider.ts:103:30)
    at Object.queryFn (useGetList.ts:75:18)
    at Object.fetchFn2 [as fn] (query.js:300:29)
(anonymous) @ useDataProvider.ts:133
(anonymous) @ useGetList.ts:75
fetchFn2 @ query.js:300
run2 @ retryer.js:95
Retryer2 @ retryer.js:156
fetch2 @ query.js:332
executeFetch @ queryObserver.js:199
onSubscribe @ queryObserver.js:40
subscribe @ subscribable.js:16
(anonymous) @ useBaseQuery.js:60
commitHookEffectListMount @ react-dom.development.js:23150
commitPassiveMountOnFiber @ react-dom.development.js:24926
commitPassiveMountEffects_complete @ react-dom.development.js:24891
commitPassiveMountEffects_begin @ react-dom.development.js:24878
commitPassiveMountEffects @ react-dom.development.js:24866
flushPassiveEffectsImpl @ react-dom.development.js:27039
flushPassiveEffects @ react-dom.development.js:26984
performSyncWorkOnRoot @ react-dom.development.js:26076
flushSyncCallbacks @ react-dom.development.js:12042
commitRootImpl @ react-dom.development.js:26959
commitRoot @ react-dom.development.js:26682
finishConcurrentRender @ react-dom.development.js:25981
performConcurrentWorkOnRoot @ react-dom.development.js:25809
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
query.js:358 Error: The dataProvider threw an error. It should return a rejected Promise instead.
    at Proxy.<anonymous> (useDataProvider.ts:135:31)
    at Object.queryFn (useGetList.ts:75:18)
    at Object.fetchFn2 [as fn] (query.js:300:29)
    at run2 (retryer.js:95:31)
    at new Retryer2 (retryer.js:156:3)
    at Query2.fetch2 [as fetch] (query.js:332:20)
    at QueryObserver2.executeFetch (queryObserver.js:199:37)
    at QueryObserver2.onSubscribe (queryObserver.js:40:14)
    at QueryObserver2.subscribe (subscribable.js:16:10)
    at useBaseQuery.js:60:32
```

I am following the document for set filter prop, But error throw above error

<img width="772" alt="image" src="https://user-images.githubusercontent.com/3498786/230045850-4421d585-276a-4acc-828c-0dffbdb649b2.png">

**Comment by TangMonk** [comment]
> Please follow the issue template

updated

**Comment by djhi** [comment]
Thanks for reporting this. Please provide a sample application showing the issue by forking the following CodeSandbox (https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple).

**Comment by fzaninotto** [comment]
Did you, by any chance, misspell `'filters` for `filter`? 

```diff
export const PostList = () => (
-   <List filter={postFilters}>
+   <List filters={postFilters}>
        ...
    </List>
);
```

**Comment by TangMonk** [comment]
> ```diff
> 
> ```

oh, shit, I got

**Comment by TangMonk** [comment]
G
