### ISSUE TITLE
DatagridConfigurable does not support react element as label on fields

### ISSUE THREAD

**Issue by tdesmet** [marmelab/react-admin#8843]
**What you were expecting:**
Usingthe localStorageStore and a DatagridConfigurable with a Field that has a react element as a label should work.

**What happened instead:**
An error is give: uncaught TypeError: Converting circular structure to JSON
This happens because the DatagridConfigurable tries to store the columns with their labels in localStorage via the localStorageStore.
It tries to json serialize the react component passed to the label property.

**Steps to reproduce:**
Create a DatagridConfigurable with a field that uses a react component for the label.

**Related code:**
https://stackblitz.com/edit/github-1t2afp?file=src/users/UserList.tsx

```
    <DatagridConfigurable
          rowClick={rowClick(permissions)}
          expand={<UserEditEmbedded />}
          bulkActionButtons={<UserBulkActionButtons />}
        >
          <TextField
            source="id"
            label={TooltipLabel('Id', <>{'tooltip text'}</>)}
          />
          <TextField source="name" />
          {permissions === 'admin' && <TextField source="role" />}
        </DatagridConfigurable>
```

**Other information:**
There is a discrepancy between the accepted types of label on a field and label in ConfigurableDatagridColumn.
A field label accepts `string | ReactElement | boolean` for the label.
ConfigurableDatagridColumn which is stored in the store by DatagridConfigurable accepts only a string for the label.

**Environment**

* React-admin version: 4.9.3
* Last version that did not exhibit the issue (if applicable):
* React version: 17.0.0
* Browser: Google Chrome Version 112.0.5615.86 (Official Build) (64-bit)
* Stack trace (in case of a JS error):
```
uncaught TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Object'
    |     property '_context' -> object with constructor 'Object'
    --- property 'Provider' closes the circle
    at JSON.stringify (<anonymous>)
    at setItem (localStorageStore.ts:114:1)
    at Object.current (useStore.ts:73:1)
    at useEvent.ts:25:1
    at DatagridConfigurable.tsx:80:1
    at commitHookEffectListMount (react-dom.development.js:23150:1)
    at invokePassiveEffectMountInDEV (react-dom.development.js:25154:1)
    at invokeEffectsInDev (react-dom.development.js:27351:1)
    at commitDoubleInvokeEffectsInDEV (react-dom.development.js:27330:1)
    at flushPassiveEffectsImpl (react-dom.development.js:27056:1)

react-dom.development.js:18687 The above error occurred in the <DatagridConfigurable> component:

    at DatagridConfigurable (http://localhost:3000/static/js/bundle.js:153880:26)
    at div
    at http://localhost:3000/static/js/bundle.js:20693:66
    at Paper (http://localhost:3000/static/js/bundle.js:48838:82)
    at http://localhost:3000/static/js/bundle.js:20693:66
    at Card (http://localhost:3000/static/js/bundle.js:34110:82)
    at div
    at div
    at http://localhost:3000/static/js/bundle.js:20693:66
    at ListView (http://localhost:3000/static/js/bundle.js:152888:18)
    at ListContextProvider (http://localhost:3000/static/js/bundle.js:122426:18)
    at ResourceContextProvider (http://localhost:3000/static/js/bundle.js:125808:21)
    at ListBase (http://localhost:3000/static/js/bundle.js:122266:21)
    at List (http://localhost:3000/static/js/bundle.js:152473:21)
```

**Comment by slax57** [comment]
Reproduced, thanks!

**Comment by igor-adzz** [comment]
I'm getting the same error when trying to use a `React Component` as a `Label` in a `DatagridConfigurable`.

**Comment by fzaninotto** [comment]
I think this is a limitation of DatagridConfigurable that we should document but won't fix, as I don't see how we could do it.

**Comment by lvernaillen** [comment]
If a `ReactElement` is used instead of a `string` or `boolean` as input field label of a grid, would it be possible to take the `label` prop of that `ReactElement`?
That would allow support of custom components as long as that component has a `label` prop itself.

Example:
```
<DatagridConfigurable>
  <TextField
     source="id"
     label={<MyCustomLabelComponent label="someLabel" />} 
   />
  <TextField source="name" />
</DatagridConfigurable>
```

**Comment by slax57** [comment]
@lvernaillen 's idea seems good to me. What do you think @fzaninotto ?

**Comment by fzaninotto** [comment]
No, that would be too much child inspection. We tend to move away from that.

**Comment by tdesmet** [comment]
how about adding a fallback labelText prop on fields, so that if the label is a react element there is something to fallback to in this case?

**Comment by lvernaillen** [comment]
This issue has been labeled documentation, but wanted to check if this is still correct.
@fzaninotto What about @tdesmet's last suggestion to add a fallback `labelText` prop?

No need for child inspection in that case.
In places where you need to render the label component, you take the `label` prop,
in places where you need a string representation of a field (such as when serializing to localStorage for column selection), you take the `labelText` prop if it is not undefined.

**Comment by fzaninotto** [comment]
What's different between naming this prop `source` and `labelText`?

**Comment by tdesmet** [comment]
My proposal is that in the Common Field Props you add a new prop with for example the name `labelText` that can only be a string and acts as a fallback for the cases where only a string can be used and not a ReactElement
For example in dataGridConfigurable you can then check if label is an element and if it is see if labelText is available.

And why would I not use source? because source is the name of the property on my record: 
for example I have one named unitPrice but as a label I would like to show Price without the Unit. And in the header of the datagrid I use a react element because I want to add a custom icon and a tooltip on this icon.

**Comment by lvernaillen** [comment]
`labelText` would be used by react-admin when `label` prop of the field is a `ReactElement` or is `false` AND only a string representation can be used in that specific place (for example the select columns popup of `DatagridConfigurable`).

Even without a new prop, I think this is a bug.
- When I set `label={false}` then react-admin shows no label in the datagrid column header and does a fallback to `source` in the select columns popup. That is correct, otherwise I'm not able to see what column the switch or reorder glyph is for in that popup.
- When I set `label={<SomeComponent/>}` then react-admin crashes. No fallback to `source` here...

In my opinion the latter example is a bug. At least the fallback to `source` should occur there, preventing a crash.
Additionally a new optional `labelText` prop (type string) would allow users to customize the label in that scenario. That would inject `labelText` in the fallback tree. `label` -> `labelText` - > `source`.
