### ISSUE TITLE
Error: (0 , react_1.createContext) is not a function - NextJS configuration problem

### ISSUE THREAD

**Issue by donghhan** [marmelab/react-admin#9189]
**What you were expecting:**
I am connecting to the NextJS (^13.14.16) with React-Admin package.

**What happened instead:**
Got error. Seems like version collision.

```
- error TypeError: (0 , react_1.createContext) is not a function
    at __webpack_require__ (/Users/apensia/dev/negative/.next/server/webpack-runtime.js:33:43)
    at __webpack_require__ (/Users/apensia/dev/negative/.next/server/webpack-runtime.js:33:43)
    at __webpack_require__ (/Users/apensia/dev/negative/.next/server/webpack-runtime.js:33:43)
    at __webpack_require__ (/Users/apensia/dev/negative/.next/server/webpack-runtime.js:33:43)
    at __webpack_require__ (/Users/apensia/dev/negative/.next/server/webpack-runtime.js:33:43)
    at eval (./src/components/admin/AdminApp.tsx:7:69)
    at (rsc)/./src/components/admin/AdminApp.tsx (/Users/apensia/dev/negative/.next/server/_rsc_src_components_admin_AdminApp_tsx.js:11685:1)
    at Function.__webpack_require__ (/Users/apensia/dev/negative/.next/server/webpack-runtime.js:33:43)
```

**Related Code**

I am using page router

```tsx
// src/components/admin/AdminApp.tsx

import { Admin, Resource, ListGuesser, EditGuesser } from "react-admin";
import jsonServerProvider from "ra-data-json-server";

const dataProvider = jsonServerProvider("https://jsonplaceholder.typicode.com");

export default function AdminApp() {
  return (
    <Admin dataProvider={dataProvider}>
      <Resource
        name="users"
        list={ListGuesser}
        edit={EditGuesser}
        recordRepresentation="name"
      />
    </Admin>
  );
}

```

```tsx
// src/app/admin/page.tsx

import { NextPage } from "next";
import dynamic from "next/dynamic";

const AdminApp = dynamic(() => import("@/components/admin/AdminApp"), {
  ssr: false,
});

const AdminPage: NextPage = () => <AdminApp />;

export default AdminPage;

```

**Environment**

* React-admin version: ^4.13.0
* Last version that did not exhibit the issue (if applicable): ^4.13.0
* React version: 18.2.0
* Browser: Chrome
* Stack trace (in case of a JS error):

**Comment by donghhan** [comment]
I was stupid. Didn't include `'use client';` on top. Closing issue.
