### ISSUE TITLE
Supporting Mobile Devices using useMediaQuery in the tutorial doesn't work

### ISSUE THREAD

**Issue by KulaGGin** [marmelab/react-admin#9810]
**What you were expecting:**
Support mobile devices using `useMediaQuery(theme => theme.breakpoints.down('sm'));`

**What happened instead:**
Error:
```
ERROR
Cannot read properties of null (reading 'breakpoints')
TypeError: Cannot read properties of null (reading 'breakpoints')
    at http://localhost:3000/static/js/bundle.js:417:96
    at useMediaQuery (http://localhost:3000/static/js/bundle.js:5276:50)
    at PostList (http://localhost:3000/static/js/bundle.js:417:80)
    at renderWithHooks (http://localhost:3000/static/js/bundle.js:119114:22)
    at mountIndeterminateComponent (http://localhost:3000/static/js/bundle.js:123085:17)
    at beginWork (http://localhost:3000/static/js/bundle.js:124388:20)
    at HTMLUnknownElement.callCallback (http://localhost:3000/static/js/bundle.js:109370:18)
    at Object.invokeGuardedCallbackDev (http://localhost:3000/static/js/bundle.js:109414:20)
    at invokeGuardedCallback (http://localhost:3000/static/js/bundle.js:109471:35)
    at beginWork$1 (http://localhost:3000/static/js/bundle.js:129369:11)
```

**Steps to reproduce:**
Follow the [Supporting Mobile Devices](https://marmelab.com/react-admin/doc/3.19/Tutorial.html#supporting-mobile-devices) section in the tutorial.

**Related code:**
When I replace PostList variable in my code with what is said in the tutorial:
```
export const PostList = (props) => {
    const isSmall = useMediaQuery(theme => theme.breakpoints.down('sm'));
    return (
        <List {...props}>
            {isSmall ? (
                <SimpleList
                    primaryText={record => record.title}
                    secondaryText={record => `${record.views} views`}
                    tertiaryText={record => new Date(record.published_at).toLocaleDateString()}
                />
            ) : (
                <Datagrid>
                    <TextField source="id" />
                    <ReferenceField label="User" source="userId" reference="users">
                        <TextField source="name" />
                    </ReferenceField>
                    <TextField source="title" />
                    <TextField source="body" />
                    <EditButton />
                </Datagrid>
            )}
        </List>
    );
}
```

I get the error:
![vivaldi_BIkC3hUhVZ](https://github.com/marmelab/react-admin/assets/16989713/f102f31e-8573-4ccf-a17b-d1dccbbed837)

Project with the issue: [React Project Example.zip](https://github.com/marmelab/react-admin/files/15176307/React.Project.Example.zip)

**Environment**

* React-admin version: react-admin@4.16.16
* React version: react@18.3.1
* Browser: Vivaldi

**Comment by fzaninotto** [comment]
Same answer as for your other issue, #9809
